### ISSUE TITLE
storage_t::get wiki signature is outdated

### ISSUE THREAD

**Issue by soroshsabz** [fnc12/sqlite_orm#293] opened 2019-05-10 15:05 UTC
ITNOA

`storage_t::get` function signature is `O get(Ids ...ids)` but wiki page is `O get(I id);` so I think it is outdated and useful to update that and make example with composite key and usage of variant of this function.

thanks

**Comment by soroshsabz** [comment] 2019-05-10 15:05
related to #292

**Comment by fnc12** [comment] 2019-05-10 18:41
Please check it out https://github.com/fnc12/sqlite_orm/wiki/storage_t::get

**Comment by soroshsabz** [comment] 2019-05-11 14:40
@fnc12 thanks for changing, I think it is good to add another example in wiki for composite key scenario

👍

**Comment by fnc12** [comment] 2019-06-05 09:24
I think that page in wiki about composite key will just copy [composite key example](https://github.com/fnc12/sqlite_orm/blob/master/examples/composite_key.cpp) so it is not required so much.
Also is the current issue actual?

**Comment by soroshsabz** [comment] 2019-06-05 15:05
@fnc12 Ok you right but I think wiki is good and easier to read than example cpp files, the wiki can more descriptive and more detailed about composite key.

**Comment by fnc12** [comment] 2019-06-05 15:14
I don't understand what to write about in wiki in composite key article. If user knows how to use foreign key he/she will understand everything from the example - just pass two keys instead of one and that is all. What words you want to see in composite key article?

**Comment by fnc12** [comment] 2019-06-05 17:02
Closing cause the issue is completed

**Closed by fnc12** 2019-06-05 17:02 UTC
Labels: wiki
