### ISSUE TITLE
Support relation

### ISSUE THREAD

**Issue by soroshsabz** [fnc12/sqlite_orm#250] opened 2019-03-30 03:32 UTC
ITNOA

I think it is good to support one-to-one, one-to-many and many-to-many relation in ORM

**Comment by fnc12** [comment] 2019-03-30 05:53
These types of relations are supported by manually. E.g. https://github.com/fnc12/sqlite_orm/blob/master/examples/subentities.cpp

**Comment by fnc12** [comment] 2019-04-16 20:36
is the issue actual?

**Comment by soroshsabz** [comment] 2019-04-19 17:51
@fnc12 I think yes :)

because I think we need a approach to get subentities like `mark` in example with full type without need to call another query, and we want to can get `student` and fill `marks` systematically

thanks

**Comment by fnc12** [comment] 2019-04-20 09:44
I though about it. How to make API for this? One of main advantages of `sqlite_orm` is that it allows developer to specify explicitly columns'/tables' names. If we make relations automatic then we need to decide how they will be managed by `sqlite_orm`. Does `class Mark` needs id or not? How foreign key column will be named? How many foreign key columns mark (subtable) must have? Not everyone uses only one column - someone uses two or more. Also there are three types of relations:
1) many to one - the same as student and marks. Relations are built with a foreign key
2) one to one - relations are also built with a foreign key but both tables can have foreign keys to each other
3) many to many - a third table it required to map ids from one table to ids from another

Different people need different options. How to perform all of this?

**Comment by fnc12** [comment] 2019-05-14 11:25
Is the issue actual?

**Comment by soroshsabz** [comment] 2019-05-14 20:16
> I though about it. How to make API for this? One of main advantages of sqlite_orm is that it allows developer to specify explicitly columns'/tables' names. If we make relations automatic then we need to decide how they will be managed by sqlite_orm. Does class Mark needs id or not? How foreign key column will be named? How many foreign key columns mark (subtable) must have? Not everyone uses only one column - someone uses two or more. Also there are three types of relations:
> 
> many to one - the same as student and marks. Relations are built with a foreign key
> one to one - relations are also built with a foreign key but both tables can have foreign keys to each other
> many to many - a third table it required to map ids from one table to ids from another
> 
> Different people need different options. How to perform all of this?

I don't know what to say, I think it is very good and important feature for ORM that provide native solution for all three type of relation and because each of us using C++ and C++ is very flexible and have zero cost principle, I think it is good to some metaprogramming configuration mechanism that get decision power to user to permit `sqlite_orm` make automatically columns/tables name or not (or enable relation or not ) or something between them

**Comment by soroshsabz** [comment] 2019-05-14 20:17
> Is the issue actual?

yes of course

**Comment by majidkamali1370** [comment] 2019-05-27 16:40
@fnc12 Hi.
I need this feature and I thought about it.
1. One-to-One
Consider foreign_key.cpp file at [line 23](https://github.com/fnc12/sqlite_orm/blob/master/examples/foreign_key.cpp#L23)
It can be like this instead:
```cpp
std::shared_ptr<Artist> trackArtist;
```
because Artist and Track both are registered via `make_table` and have ID columns and sqlite_orm knows which column it is, I think it can be implementable (even without changing public API, just change behavior of `foreign_key` function).
PS: It is usually a bad design to put two tables' foreign keys in eachother. usually there is a slave entity that referes to a master one. In our case, `Track` is the slave entity and `Artist` is master. (I just come up with names master and slave :smile: )
2. Many-to-One:  I think there is enough to just change the `std::shared_ptr` or `std::unique_ptr` with `std::vector` or some user defined container.
```cpp
struct Artist {
    int artistId;
    std::vector<Track>;
};
```
3. Many-to-Many: two Many-to-One relations

What's your opinion?

**Comment by fnc12** [comment] 2019-05-28 10:29
@majidkamali1370 Hi. Thanks for using the lib.
Your suggestions are very good and useful but there are some issues:
1. As contributors of the library we must think about all cases not only about ones which use `std::shared_ptr` as a pointer to a subentity. There can be people who does not bind subentities with pointer/reference but just want to keep int id as a member. We need to make API suitable for both. Next issue: why `std::shared_ptr`? Why not `std::unique_ptr` or reference or event raw pointer? I know that raw pointer is an old style but raw pointer can be treated a a nullable reference which is a very popular case. Also developers can use custom smart pointers. How to make it fit everyone? If you have an idea I'd like to listen to it.
2. Same thing about pointer types. This is just what you got used to but not everyone
3. Same...

Too many options and no way to specify every of them. I'd like to make it but I need a perfect way cause adding only one option to public API will cut off all others until next major release

**Comment by majidkamali1370** [comment] 2019-05-29 07:27
@fnc12 Hi.
> There can be people who does not bind subentities with pointer/reference but just want to keep int id as a member.

The problem is that pure `int` can not be null [Impedance Mismatch](url). Although there can be `not null` foreign keys` actually.
I have 2 ideas about this:
1. use a specific type for foreign keys `foregn_key_t` with the following API:
```cpp
foreign_key_t <int, Artist> artistId; // in class Track
...
if(artistId) // usage1. check for nullity. borrowed from std::optional
...
*artistId = 5; // usage2. cast to template type (int). borrowed from std::unique_ptr, std::shared_ptr, std::optional
...
artistId->name .... // usage3. access to Artist class. loads lazily. borrowed from std::unique_ptr, std::shared_ptr
```
In this Idea, I didn't consider `foreign_key(&Track::trackArtist).references(&Artist::artistId)` in `make_table` function. With this consideration, there can be even more fluent and easier API.
2. Specialize a class template with `std::unique_ptr`, `std::shared_ptr`, `std::optional` etc. that can be used with a user-defined type either: (following code might have errors :D, I don't know templates very well)
```cpp
template <class OuterType, class InnerType> // For example OuterType = std:: shared_ptr, InnerType = int -> define std::shared_ptr<int> in class Track.
class foreign_key_t {
  bool is_null() { return true; }
  InnerType value() { return InnerType{}; }
};
// Partial specialize for std::optional
template <class InnerType>
class foreign_key_t {
  std::optional<InnerType> o_;
  bool is_null() { return (bool)o_; }
  InnerType value() { return *o_; }
};
// Partial specialize for std::shared_ptr
...
// Partial specialize for std::std::uniqu_ptr
...
// Partial specialize for some user-defined class
...
```
This idea is like library's ability to use a user-defined type as class member type (e.g. `QString`), which one needs to specialize `type_printer`, `statement_binder` and `row_extractor`. Library uses `foreign_key_t` under the hood.
But in both cases, I don't think using raw pointers can be accomplished.

**Comment by fnc12** [comment] 2019-05-29 07:31
Yes, `int` cannot be null but `std::optional<int>` can. Why do you ask me to reimplement `std::optional`/`boost::optional` while it already exists and works well with `sqlite_orm`? You can have a foreign key member with a nullable type (`std::shared_ptr`, `std::unique_ptr` or `std::optional`). `std::shared_ptr` and `std::unique_ptr` work out of box and `std::optional` must be bounded manually but it works well. If you have any issues of using it please feel free to ask about it. 
Also SQLite never creates id equals to zero so zero id in foreign key member means no object.

**Comment by majidkamali1370** [comment] 2019-05-29 07:37
> std::shared_ptr and std::unique_ptr work out of box and std::optional must be bounded manually but it works well.

I think you don't agree idea 1. Me too :smile: 
In idea number2: I say create an official machanism for adding `std::optional` AND other user defined types. In this case, the work is actually done in `foreign_key(&Track::trackArtist).references(&Artist::artistId)`

**Comment by fnc12** [comment] 2019-05-29 07:39
The official mechanism exists. You can bind custom type and specify whether they nullable. Please check https://github.com/fnc12/sqlite_orm/blob/master/examples/enum_binding.cpp and https://github.com/fnc12/sqlite_orm/blob/master/examples/nullable_enum_binding.cpp

**Comment by majidkamali1370** [comment] 2019-05-29 07:48
> The official mechanism exists.

Yes but template type must be a type that can be presented by string, integer or real number (because of `text_printer` etc.).
Is there a way to use a `make_table`-registered class such as Artist? No.

Idea 3:
Is there a way to **extend** this mechanism for such classes?
A dirty solution and idea would be using json string representation of refered class in cases where `string` or `char*` is needed.

**Comment by fnc12** [comment] 2019-05-29 10:09
No, template type must be any type which can be bound to a storage. If you can make a column with such a type then you can make a foreign key with this type.

It looks like you want to store a whole object in a single column. This is not what relations databases are created for. Assume you have two tables `tracks` and `artists` and want a track to be a part of artist table as a column:
```
artists
======
id: int
name: text
tracks: json-string
```
and you want to select all tracks that have length(name) < 10 what are you going to do?

**Comment by majidkamali1370** [comment] 2019-05-29 12:44
> It looks like you want to store a whole object in a single column.

Absolutly not. I mean when the user writes something like this:
```cpp
std::shared_ptr<Artist> artistId; // In class Track
```
sqlite_orm automatically finds relation between these two classes, because of this line:
```cpp
foreign_key(&Track::trackArtist).references(&Artist::artistId)
```
I want that user accesses the articleId as an `int` (this is what it is now, but with change of `Artist` to `int` in first snippet).
However with some mechanism (like operator-> for instance), user can access corresponding `Artist` object.

**Comment by fnc12** [comment] 2019-05-29 14:13
Ok, I see. But there are still unclosed issues in your idea. What if we have selected one track which has field `std::shared_ptr<Artist> artistId;` which is also selected implicitly and then we select another track with the same `artistId`. Do you expect that both `artistId`'s will point to the same object?
Another question: what if after all these selections we call `get<Artist>` by same id and fetch artist object. So the object will be different cause `get` returns not shared pointer. Is it ok for you? 
Main principle of the lib is mapping member pointers to columns. So you want to have a pointer which stores a whole object. Also there can be cross references. How do you want to implement such an issues?

**Comment by majidkamali1370** [comment] 2019-05-29 14:54
> Ok, I see. But there are still unclosed issues in your idea. What if we have selected one track which has field std::shared_ptr<Artist> artistId; which is also selected implicitly and then we select another track with the same artistId. Do you expect that both artistId's will point to the same object?

Considerable question. How other ORMs like hibernate manage this kind of issue?
I think using an internal cache of `std::shared_ptr`s can be useful.
```cpp
std::shared_ptr<Artist> artistId; // in class Track
...
track.artistId->name; // First usage. loads Artist with corresponding id into internal cache and returns its name
...
// Second usage. returns Artist with corresponding id. returns from cache
storage.get_pointer<Artist>(anAristId) // anArtistId == track.artistId
...
// Third usage. returns Artist with corresponding id. returns from cache
// NOTE bad practice. because of returning dereferenced internal shared_ptr
// NOTE change get return type or deprecate it
Artist artist = storage.get<Artist>(anAristId) // anArtistId == track.artistId
```
> Also there can be cross references. Track stores artist and artist stores his/her tracks. How do you want to implement such an issues?

This is very complex but I think it can be managed with internal cache.

**Comment by fnc12** [comment] 2019-05-29 16:51
1) `storage.get_pointer<Artist>` returns not `shared_ptr` so it cannot operate with `std::shared_ptr` cache. Also cache for all objects all over the storage is a very bad idea cause it will be very slow when amount of objects is huge.
2) deprecating `T get<T>` and forcing everyone to use only shared memory is a very bad practice cause C++ is about freedom. If you want all objects to be stored in shared memory only please use Java, Swift, ObjC or any other language with dynamic types. `T get<T>` is the easiest and brilliant API and deprecating it will break this ORM.

**Comment by fnc12** [comment] 2019-05-29 16:55
If you want to obtain artists with tracks you can inherit storage and write `get` function inside your storage subclass which will implement two queries instead of one. Or you can write a simple function `getTrack` which applies storage, gets track, then gets artist by `Track::artistId` and assigns artist to `std::shared_ptr<Artist> Track::artist` created by you and not mapped to a storage

**Comment by fnc12** [comment] 2019-05-29 16:58
here is the example for it https://github.com/fnc12/sqlite_orm/blob/master/examples/subentities.cpp

**Comment by fnc12** [comment] 2019-05-29 18:45
Also how do you expect to store composite foreign key subentities in your cache?

**Comment by majidkamali1370** [comment] 2019-05-31 10:13
> Also how do you expect to store composite foreign key subentities in your cache?

That's very hard :-D
It complicates cache structure.

My actual point for suggesting internal cache:
Assume two different classes want to get the same Entity with same id. In this ORM (and many others), these two returned objects are different ones. Changing any of them and commiting to database, does not affect the others.
THIS is my biggest problem with ORM (of any kind). using some internal cache can be a solution, but as you saied, has downsides.

Using _Offline lock_ can be another solution. Can it be implemented in sqlite_orm? using a row which is hidden to orm user, but there is in database tables.

**Comment by fnc12** [comment] 2019-05-31 12:31
There is no need to hide something from user cause once user knows that orm doesn't return some data which exists in raw database he/she will get confused. Just look on all your ideas in this issue and try to analyze pros and cons. Looks like it would more correctly to write code just like it is done in [subentities example](https://github.com/fnc12/sqlite_orm/blob/master/examples/subentities.cpp) and give up idea with internal cache will all objects duplicating data from database. Making such a cache will make a second database located in memory stored in `std::map` which will affect almost all queries. And you want all this just because you don't want to write two functions. I know that `Realm.Swift` does exactly what you want. But once something goes wrong with this database you don't know how data is stored cause everything is performed by lib. You don't know how foreign key table is named, how table relation is implemented and you cannot debug it with an outer tool. `sqlite_orm` is not about it. It is about clarity and power.

**Comment by fnc12** [comment] 2019-06-20 15:34
If there is no new idea for subentities I close the issue just like I did with all previous ones marked with `subentities`. There is no idea about comfortable implementation if this feature for everyone right now

**Closed by fnc12** 2019-06-20 15:34 UTC
Labels: subentities
