### ISSUE TITLE
provide "user define function"

### ISSUE THREAD

**Issue by paineZhang** [fnc12/sqlite_orm#132] opened 2018-03-26 11:15 UTC
Hi!
Could you provide "user define function" function?
Refer to the link: http://sqlite.org/c3ref/create_function.html and http://sqlite.org/c3ref/create_collation.html
This is usually very helpful for complex comparisons, sorting, etc. /:)

**Comment by fnc12** [comment] 2018-03-26 17:39
Hm, this is very interesting. I didn't know about custom collation before. Do you have concrete example of custom collating function? 
I've been thinking about custom functions a lot of time already. I see two ways of implementing it:
1) To define a custom function one have to define a class (say 'MyFunc`) derived from kinda `sqlite_orm::function<return_type, args_count>`. This class must have a cast to `std::string` operator overloaded which must return function name. To specify this function in query one have to write `storage.select(MyFunc(&User::id)); To bind this custom function to a storage you must add `custom_functions<MyFunc>` in `make_storage` as an argument.
2) Add `custom_function("my_func", [](int arg0, std::string arg1){ .... })` into `make_storage` and call it with `storage.select(custom("my_func", &User::id, &User::name));`. Easier to write but you'll need to write function name again and again every time.

What do you think about that? You can offer your own option if you have one. Thanks

**Comment by data-man** [comment] 2018-03-26 18:05
@fnc12 
Maybe can useful https://github.com/utelle/wxsqlite3/blob/master/src/wxsqlite3.cpp#L3864

**Comment by paineZhang** [comment] 2018-03-27 02:50
About "collation":
```
//define collation function
int pinyin_cmp(
    void *usr_arg,
    int nKey1, const void *pKey1,
    int nKey2, const void *pKey2)
{
    int n = nKey1 < nKey2 ? nKey1 : nKey2;
    return pinyin_strncmp(pKey1, pKey2, n + 1);
}

//create collation
sqlite3_create_collation(db, "_pinyin_collation", SQLITE_UTF8, nullptr,pinyin_cmp);

//table
 create table person(name text);

//select
select * from person order by name collate pinyin;
```
About custom function.
The library's style is bind name to type，and user type at other place.This is reflected in make_storage、make_table、make_column,etc.Style consistency, that's important.
I mean, provide `make_function` funciton.It look like `make_function("func_name", func_object/class static func)` at bind,and `storage.select(custom( func_object/class static func, &User::id, &User::name))` at use.

**Comment by paineZhang** [comment] 2018-03-27 03:07
About custom collation:
```
//define a collation function
int pinyin_cmp(void* usr_arg, int n1, const void* p1, int n2, const void* p2){
 ....
}

//create in sqlite3
sqlite3_create_collation(sqlite_handle,"_pinyin_cmp", SQLITE_UTF8, nullptr, &pinyin_cmp);

//table
create table person(name text)

//use
select * from person order by name collate pinyin_cmp;
```
About custom function.
I think the consistency of style is very important.So, I prefer to the second solution.And it is better to use function object instead of name.

**Comment by fnc12** [comment] 2018-03-27 05:27
@paineZhang what do you mean `function object instead of name`? Can you provide example code?

**Comment by paineZhang** [comment] 2018-03-27 06:39
`storage.select(custom("my_func", &User::id, &User::name));`
`"my_func"` replace by some function object.

sqlite3 bind function address with name,and use  function with name.
sqlite_orm's style is bind type with name, and use type only.
So,I think `storage.select(custom(&XXX_fun, &User::id, &User::name))it;` is better.Although it may be somewhat awkward in usage. /:(
And , there may be some problems, for example, why record a function address in sqlite_orm.
It may be helpful only to check the type of parameters at the compile stage.

**Comment by fnc12** [comment] 2018-03-27 18:02
@paineZhang I guess I know the best way. First of all we need to know whether custom functions/collations binding must be static or dynamic. Static means functions and collations are provided in `make_storage` only and dynamic means that one can bind any function/collation at any point of time like this `storage.add_custom_function("my_func", [](std::string arg0, int arg1){...});`. So it will be very nice to implement both method to allow developers act as they want. What do you think?

**Comment by paineZhang** [comment] 2018-03-28 01:37
Well, that's perfect.
The "dynamic" is exactly what I need in my current coding work of high-level interfaces.And I was originally planning to provide a method when calling select. Use like : 
```
template<typename T, typename K, typename Fun=void>
vector<T> get(const K& _key, Fun& _fun){
    _fun.name() ;
    _fun.call();
}
```

**Comment by fnc12** [comment] 2018-03-29 05:08
I don't understand the code you provided. What raw query do you mean under this code? I assume custom function will be called like this:

```c++
storage.bind_custom_function("my_func", [](int arg0){ ... });
auto rows = storage.select(custom_function("my_func", &User::id));
```
or in case of static function:

```c++
struct MyFunc : public sqlite_orm::function<1> {   // 1 argument
    operator std::string() const {
        return "my_func";
    }
    
    int operator()(int arg0) const {
        return arg0 * 2;    // dummy body
    }
};
auto storage = make_storage("db.sqlite", make_table(...), custom_functions<MyFunc>());

auto rows = storage.select(custom_function<MyFunc>(&User::id));
```

**Comment by paineZhang** [comment] 2018-03-29 05:56
The "static function" case.

**Comment by fnc12** [comment] 2018-04-07 09:58
@paineZhang please check out [custom-collation branch](https://github.com/fnc12/sqlite_orm/tree/feature/custom-collations) and new test in tests.cpp `testCustomCollate()` example. Tell me whether it is ok or not. I'll be developing other features within the issue. Thanks

**Comment by fnc12** [comment] 2018-04-07 18:46
@paineZhang I'm trying to implement custom functions and I got one question: how do you expect to separate aggregate and scalar functions?

**Comment by paineZhang** [comment] 2018-04-08 02:35
About custom collate, that ok with usage.Is it gonna work on `order_by`?

About `separate aggregate and scalar functions`.How about this: 
The `storage` provide a function like `storage.function(string bind_name, args...)`.It is usage like `count`.

Honestly, it's really hard to separate them when use bind,unless developers can provide a clear purpose for them.And need developer's self to make sure is using the right way.It is difficult to provide such safeguards.I can't think of a good idea at the moment. /:<

**Comment by paineZhang** [comment] 2018-04-08 07:01
The first.
I don't understand why there is a need to differentiate between aggregate and scalar functions.The second way makes them seem indistinguishable. /@.@

**Comment by paineZhang** [comment] 2018-04-08 07:57
Aha!
All right.Then there has to be a explicit way for bind./:)

**Comment by fnc12** [comment] 2018-04-08 07:57
@paineZhang Ok, I've thought about it too

**Comment by fnc12** [comment] 2018-04-12 17:26
@paineZhang please check out the latest commit in `dev` branch - now one can you custom collations with `ORDER BY`

**Comment by paineZhang** [comment] 2018-04-13 02:25
OK.They works properly.

**Comment by fnc12** [comment] 2018-06-04 19:47
Good news: I understand the difference between custom simple functions and custom aggregate functions. [Here](http://souptonuts.sourceforge.net/readme_sqlite_tutorial.html) you can find an excellent article. In short: `max(id)` is aggregate cause it works with table data but `max(1, 4.5, id)` is simple cause it works with simple data and has > 1 arguments. In other words aggregate function is a transformator for row entry but simple function is a function that we often use in common programming languages. E.g. `std::max`, `std::sin`

**Comment by paineZhang** [comment] 2018-06-05 01:28
Roger that.
Here are 100 praises. /:>

**Comment by fnc12** [comment] 2018-10-21 17:54
Holy crap. I don't know how exactly I need to implement custom functions. There are two major options:
1) static - functions are define in `make_storage` and cannot be redefined after storage creation. 
2) dynamic - functions can and must be added after `make_storage` call and can be removed
What do you think?

**Comment by fnc12** [comment] 2019-07-11 05:32
hey @paineZhang . I started to work on custom functions again. The issue is really non trivial. So the only option I know how to implement right now is static and scalar with determinate amount of arguments. So this solution skips dynamic function creating, aggregate functions and scalar functions with a variadic amount of arguments. I shall provide an example code here soon

**Comment by fnc12** [comment] 2019-07-11 08:53
```c++
auto storage = make_storage("db.sqlite",
                               make_table(...),
                               functions(make_function("SQRT", [](double arg){
                                      return std::sqrt(arg);
                               }),
                                                make_function("LOG10", [](double arg){
                                      return std::log10(arg);
                               }));
```

**Comment by fnc12** [comment] 2019-07-11 16:52
About difference between scalar and aggregate functions.
Scalar function examples: `substr`, `random`, `sin` etc. Scalar functions are common function which take some arguments and evaluate value at once.
Aggregate functions examples: `count`, `sum`, `avg`. Aggregate functions take a bunch of data: column at a result of a query.
More clare example:
```sql
SELECT substr(name)
FROM users
```
will give you result with N rows where N is equal to amount of rows in the `users` table. It is how scala functions work.
But 
```sql
SELECT avg(id)
FROM users
```
will not give you N rows but only 1 row cause `avg` is an aggregate function. it takes the whole column, iterates over it and evaluates average value. This is the difference. Also functions `max` and `min` are both aggregate and scalar. `max` with a single argument with a column of a query result is an aggregate function and evaluates max value of a given bunch of value. But `max` with > 1 arguments is a scalar function - it returns a max value of a given arguments at once without iterating over rows (cause there are no rows).
Next: aggregate function must have a body of a single iteration and a finalize routine. It means two lambdas. Also aggregate function must transfer some data between iteration routines and final routine. Scalar function have no data to transfer. I guess that some people require aggregate functions support in `sqlite_orm` and I have no idea how to implement API for it. If you have one please feel free to share it with me and the community. Thanks

**Comment by fnc12** [comment] 2020-06-02 12:50
Damn. During this issue existence the third type of functions appeared: `WINDOW` functions. I shall add only scalar and aggregate custom function support in this issue. There is [another issue](https://github.com/fnc12/sqlite_orm/issues/475) for `WINDOW` functions.

**Comment by fnc12** [comment] 2021-07-06 21:02
everyone please review the implementation https://github.com/fnc12/sqlite_orm/pull/748

**Comment by fnc12** [comment] 2021-07-07 11:29
merged. Next will be aggregate functions

**Comment by fnc12** [comment] 2021-07-09 18:34
next PR with aggregate functions is ready https://github.com/fnc12/sqlite_orm/pull/749

**Comment by fnc12** [comment] 2021-07-10 08:03
aggregate functions are available in `dev` branch. Please check it out if someone is still here. Next will be scalar and aggregate functions with variadic templates

**Comment by fnc12** [comment] 2021-07-11 11:37
variadic scalar functions are on their way https://github.com/fnc12/sqlite_orm/pull/751

**Comment by fnc12** [comment] 2021-07-21 15:11
so finally scalar and aggregate functions with variadic arguments merged. Now `sqlite_orm` support both scalar and aggregate functions with both static and variadic arguments. Now I'll add an example and close the issue

**Comment by fnc12** [comment] 2021-07-26 13:32
so I've merged an example file https://github.com/fnc12/sqlite_orm/blob/dev/examples/user_defined_functions.cpp . Please check it out. I am closing this issue. If anyone finds something wrong please reopen it or create a new one

**Closed by fnc12** 2021-07-26 13:32 UTC
Labels: enhancement
