### ISSUE TITLE
do you support bitwise operator in where clause?

### ISSUE THREAD

**Issue by JCYang** [fnc12/sqlite_orm#476] opened 2020-03-07 01:55 UTC
My app run into a scenario where a bitwise & is needed within the where clause, but the compiler complain that no such operator& is available, is that a missed feature or bug?

**Comment by JCYang** [comment] 2020-03-07 01:57
FYI, I'm not using the latest version because when I find it stable for my works, I don't have the intentions to upgrade

**Comment by k03rdt6** [comment] 2020-03-07 04:16
do you have a code snippet

**Comment by JCYang** [comment] 2020-03-07 05:24
somthing like this
`db.get_all<Table>(where(c(&Table::Flag) & f and c(&Table::ID) == id))`

**Comment by fnc12** [comment] 2020-03-07 08:08
What SQL query do you expect to run?

**Comment by fnc12** [comment] 2020-03-07 08:09
This looks like a feature noone requested before https://www.tutorialspoint.com/sqlite/sqlite_bitwise_operators.htm . I shall add it soon but you will need to upgrade the lib in your project afterwards

**Comment by JCYang** [comment] 2020-03-07 12:23
thanks, I am looking forward to the new version.
though workaround it is easy, but a native support can introduce cleaner code.

**Comment by fnc12** [comment] 2020-03-09 20:44
@JCYang hi again. Good news! I've just merged it in https://github.com/fnc12/sqlite_orm/pull/477 . Example [here](https://github.com/fnc12/sqlite_orm/blob/dev/tests/operators/bitwise.cpp)

**Comment by JCYang** [comment] 2020-03-19 15:04
> 
> 
> @JCYang hi again. Good news! I've just merged it in #477 . Example [here](https://github.com/fnc12/sqlite_orm/blob/dev/tests/operators/bitwise.cpp)

Thanks for the so fast action! Busy working on other parts/bugs of my project and is late to the test.
Just test, but the result is not pleasant yet.
My usage scenario is to store an unsigned int as bitmap in one column of the table, and use the bitwise_and in the where clause to query the desired dataset, but something like `bitwise_and(c&(MyTable::Flag), desired_bitflag)` does not work through the compiler. Maybe something need to be further fine tuned? the MyTable::Flag is unsigned int, and I strictly force the desired_bitflag as unsigned int to avoid type mismatch already. And can you support operator& overloaded as the syntax sugar?

**Comment by fnc12** [comment] 2020-03-23 16:25
@JCYang please show me detailed code to be able to reproduce your issue. Thanks

**Comment by fnc12** [comment] 2020-06-02 12:42
@JCYang are you there?

**Comment by fnc12** [comment] 2020-07-20 18:24
looks like that feature is done. Closing

**Closed by fnc12** 2020-07-20 18:24 UTC
Labels: feature
