### ISSUE TITLE
Expose get/set pragma on storage and add vacuum

### ISSUE THREAD

**Issue by jmorrill** [fnc12/sqlite_orm#120] opened 2018-03-12 02:40 UTC
I'm sorry for the blitz of suggestions today. :)

I need to set pragmas like "journal_mode" to "WAL".  I couldn't find a public way to do this, so I copied/pasted your implementation of set_pragma to the internal::storage_t class.

Also, a function to run VACUUM could be nice :).

**Comment by fnc12** [comment] 2018-03-12 05:07
ok, I'll add `PRAGMA journal_mode` from [here](https://www.sqlite.org/pragma.html#pragma_journal_mode) and vacuum function today later

**Comment by fnc12** [comment] 2018-03-13 17:39
@jmorrill I got one question about `PRAGMA journal_mode`:
how is it better to make API for it? The issue is that all older pragmas implemented have values mapped to ints. But `journal_mode` doesn't have it. I mean you cannot write `PRAGMA journal_mode = 0` for `PRAGMA journal_mode = DELETE` and `PRAGMA journal_mode = 1` for `PRAGMA journal_mode = TRUNCATE `. So I see two ways of performing API:
1) Cute way
```c++
auto storage = make_storage(...);
std::string journalMode = storage.pragma.journal_mode();   // get current journal mode
storage.pragma.journal_mode().delete_();   // set pragma journal mode = DELETE
storage.pragma.journal_mode().truncate();   // set pragma journal mode = TRUNCATE
storage.pragma.journal_mode().persist();   // set pragma journal mode = PERSIST
storage.pragma.journal_mode().memory();   // set pragma journal mode = MEMORY
// etc
```
`journal_mode()` member function returns an adapter object. This adapter performs `PRAGMA journal_mode` in cast to `std::string` operator and set in its member functions `delete_`, `truncate`, `persist`, `memory` etc. Notice that `auto journalMode = storage.pragma.journal_mode();` will NOT return string with journal mode. 
2) Simple way
```c++
auto storage = make_storage(...);
auto journalMode = storage.pragma.journal_mode();   // get current journal mode, journalMode is enum with `std::ostream& operator<<` overloaded.
storage.pragma.journal_mode(sqlite_orm::journal_mode::delete_);   // set to DELETE
storage.pragma.journal_mode(sqlite_orm::journal_mode:: truncate);   // set to TRUNCATE
// etc
```

What do you think?

**Comment by fnc12** [comment] 2018-03-15 19:06
@jmorrill just added `PRAGMA auto_vacuum` in `dev` branch. Please check it out

**Comment by fnc12** [comment] 2018-03-17 08:30
@jmorrill just added `vacuum()` member function to a storage and merged in `dev` branch. Please check out

**Comment by jmorrill** [comment] 2018-03-21 06:52
Sorry, I didn't mean to fall off the map like that.  Got sick.  And won't be able to check this out until next week. :(

On the other hand, you've made a really nice API so far and have a lot of faith in your judgement.  I'll let you know if I have any feedback when I get back on it!

Thanks again!

**Comment by fnc12** [comment] 2018-03-21 09:45
@jmorrill it's ok. I'll wait

**Comment by fnc12** [comment] 2018-04-02 20:47
the feature is done. Closing due to silence

**Closed by fnc12** 2018-04-02 20:47 UTC
Labels: enhancement
