### ISSUE TITLE
foreign key fails

### ISSUE THREAD

**Issue by nutss1** [fnc12/sqlite_orm#58] opened 2017-11-05 05:38 UTC
with the current sqlite, I see the following error when running the foreign_key.cpp example

replace query: REPLACE INTO 'artist' ("artistid", "artistname") VALUES(?, ?)
replace query: REPLACE INTO 'artist' ("artistid", "artistname") VALUES(?, ?)
sending query: INSERT INTO 'track' ("trackname", "trackartist") VALUES (?, ?)
terminate called after throwing an instance of 'std::runtime_error'
  what():  no such table: main.artistid
Aborted
I believe its because its getting main. as part of the foreign key name. not sure where the bug is - still debugging. any help?

**Comment by fnc12** [comment] 2017-11-05 07:43
Hi. Thanks for using the lib. I've just compiled and ran `foreign_key.cpp` example on my machine and it worked fine. Also this example is included in travis CI service and it works well. You can see it by this [![Build Status](https://travis-ci.org/fnc12/sqlite_orm.svg?branch=master)](https://travis-ci.org/fnc12/sqlite_orm) badge.
Tell me please which line of code fails? And your sqlite version (`storage.libversion()`). Thanks

**Comment by fnc12** [comment] 2017-11-16 13:33
@nutss1 bump. Are you there?

**Comment by fnc12** [comment] 2017-11-25 19:05
hey I couldn't repeat this bug. Either please write back or I'll close the issue due to unable to repeat

**Comment by fnc12** [comment] 2017-12-01 19:59
I'm closing the issue due to `unable to reproduce`.

**Closed by fnc12** 2017-12-01 19:59 UTC
Labels: bug
