### ISSUE TITLE
Windows compile is very hard for me

### ISSUE THREAD

**Issue by 578141611** [fnc12/sqlite_orm#435] opened 2019-12-12 12:08 UTC
I try many method to build sqilte3,but fail to build. @fnc12  can you provide dependency sqilte3 in you cmake project. thank you.

**Comment by fnc12** [comment] 2019-12-12 16:41
@578141611 sorry I don't know cmake much. Try to google it

**Comment by drescherjm** [comment] 2019-12-12 17:50
sqlite_orm is in vcpkg. That is probably the simplest way to build in Visual Studio.

**Comment by fnc12** [comment] 2019-12-12 18:31
@578141611 try this https://cppcodetips.wordpress.com/tag/including-sqlite-with-visual-studio/ . I am not sure it will work cause I don't use visual studio at all. I use mac, mac os has libsqlite3 already installed.

**Comment by fnc12** [comment] 2019-12-16 11:30
is the issue actual?

**Comment by fnc12** [comment] 2019-12-17 14:24
closing cause it is not a bug or enhancement

**Closed by fnc12** 2019-12-17 14:24 UTC
Labels: notabug
