### ISSUE TITLE
Conan package

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [fnc12/sqlite_orm#66] opened 2017-11-28 16:45 UTC
Hello,

Can yuo create Conan package for your library?

**Comment by fnc12** [comment] 2017-11-29 05:06
I think I can. Let me look trough Conan details and I'll return with a detailed answer

**Comment by fnc12** [comment] 2017-12-01 20:02
@ZaMaZaN4iK maybe you know someone who can solve the issue? It can take long time for me to do it by myself cause I never use `Conan`

BTW I move to Minsk next week

**Comment by ZaMaZaN4iK** [comment] 2017-12-02 00:22
Bincrafters team can do it. It's open community for making Conan recipes. But Bincrafters has lack of human resources :-( It's the only reason why i ask to every library author with only one question - "Please, make Conan package" :-)

>BTW I move to Minsk next week
Nice, i will be in Minsk too :-)

**Comment by AlexandrePTJ** [comment] 2018-01-16 19:20
Hi,

As I use sqlite_orm in a new project with conan, I created the package here: [conan-sqlite_orm](https://github.com/AlexandrePTJ/conan-sqlite_orm)
However to follow a regular way for packaging, I think that including semantic versionning might be a good idea.

Thanks for good work on sqlite_orm anyway !

**Comment by fnc12** [comment] 2018-01-16 19:27
Hey, this is a very good news! Thank you very much. What is required from me to finalize this issue? What do you mean "semantic versionning" exactly?

**Comment by AlexandrePTJ** [comment] 2018-01-16 19:59
There is nothing to do more to finalize this issue.
Semantic versionning is guidelines to explain how to manage version numbers. This is explained here: [https://semver.org/](https://semver.org/)

**Comment by fnc12** [comment] 2018-01-16 20:04
@AlexandrePTJ do you expect posting a release per every version in releases section in github or something else?
@ZaMaZaN4iK please check out the conan package and close the issue if everything is fine.
@AlexandrePTJ is there a way to add unit tests for this?
@AlexandrePTJ do we need to put conan file into repo?

**Comment by AlexandrePTJ** [comment] 2018-01-16 20:24
Yes package will be updated with each version of sqlite_orm.

In the process of package creation with conan, there is a step named "test_package". This is usualy is simple main which include the library but it can execute unit tests.

From my opinion, conan stuff should stay in a separate repo. That way, the library repo stay clear and packaging can evolve with disturbing library development.

**Comment by fnc12** [comment] 2018-01-16 20:26
so everyone who wants to use `sqlite_orm` with conan will need to clone [your repo](https://github.com/AlexandrePTJ/conan-sqlite_orm)? Or I got to fork it anyway?

**Comment by AlexandrePTJ** [comment] 2018-01-16 20:35
Not exactly.
Now the recipe is written, I submit it to @bincrafters and to the public repository conan-transit.
The first is to put the recipe in "good pratices" process and to maybe to makes it release under a recognized community.
The second one, is to allow anyone using conan to add the package as a dependency of its project. This is done by just adding "sqlite_orm/1.0.0@alexandreptj/stable" in a text file, then conan do all the magic (download, build if needed, install, references, ...)

**Comment by fnc12** [comment] 2018-01-17 05:14
@AlexandrePTJ that's very cool. Thank you very much. I should take much time for me if I do it.

**Comment by fnc12** [comment] 2018-02-05 20:17
closing cause issue creator isn't responding but the issue is closed

**Closed by fnc12** 2018-02-05 20:17 UTC
Labels: enhancement, help wanted

**Comment by solvingj** [comment] 2018-03-14 17:23
Thanks to @AlexandrePTJ , the package is in good shape with the 1.0 release, and has been submitted for inclusion into Conan-Center.  Here it is represented and available in Bincrafters repository. 

https://bintray.com/bincrafters/public-conan/sqlite_orm%3Abincrafters
