### ISSUE TITLE
How to write a select within a select in sqlite_orm?

### ISSUE THREAD

**Issue by juandent** [fnc12/sqlite_orm#712] opened 2021-04-24 17:33 UTC
I have this SQL statement:

```SQL
select c.id_claim, (
    SELECT count(*) > 0 
    from Invoices ii 
    WHERE ii.fkey_claim = c.id_claim and ii.fkey_INSResponse = 1
), i.fkey_INSResponse = 1, i.number 
from Invoices i 
INNER JOIN Claims c on i.fkey_claim = c.id_claim
```

and want to write it in sqlite_orm like so:

```C++
auto lines = storage.select(columns(alias_column<als_c>(&Claim::id), select(columns(alias_column<als_s>(&Invoice::id), count()), where(c(alias_column<als_s>(&Invoice::fkey_claim)) == alias_column<als_m>(&Claim::id))),
		inner_join<als_c>(on(c(alias_column<als_i>(&Invoice::fkey_claim)) == alias_column<als_c>(&Claim::id)))));
```

But throws error on compilation:

error C2027: use of undefined type 'sqlite_orm::internal::column_result_t<St,sqlite_orm::internal::inner_join_t<als_c,sqlite_orm::internal::on_t<sqlite_orm::internal::is_equal_t<sqlite_orm::internal::alias_column_t<als_i,int Invoice::* >,sqlite_orm::internal::alias_column_t<als_c,int Claim::* >>>>,void>'

what am I doing wrong?

**Comment by fnc12** [comment] 2021-04-24 17:39
`SELECT count(*) > 0 ` must be transformed to `greater_than(count<Invoice>(), 0)` but you wrote `columns(alias_column<als_s>(&Invoice::id), count())`

**Comment by juandent** [comment] 2021-04-24 18:02
yes but it has a WHERE condition:

```SQL
SELECT count(*) > 0 
    from Invoices ii 
    WHERE ii.fkey_claim = c.id_claim and ii.fkey_INSResponse = 1
```

how do we attach the where clause to get that count?

**Comment by juandent** [comment] 2021-04-24 18:15
Maybe you have a sample select within a select which I can use as help?

**Comment by juandent** [comment] 2021-04-24 21:17
I am wondering, is there support for selects inside of selects in sqlite_orm?

**Comment by juandent** [comment] 2021-04-24 21:32
Am I getting closer with this? Any help will be very appreciated...

```C++
auto otherlines = Storage::getStorage().select(columns(alias_column<als_c>(&Claim::id), storage.select(columns( alias_column<als_p>(&Invoice::id), greater_than(count<als_p>(), 0)), where(c(alias_column<als_p>(&Invoice::fkey_claim) == alias_column<als_k>(&Claim::id))))))
		inner_join<als_c>(on(c(alias_column<als_i>(&Invoice::fkey_claim)) == alias_column<als_c>(&Claim::id)));
```

**Comment by juandent** [comment] 2021-04-25 00:47
as for the placing questions repeatedly in different issues I was truly desperate for help but I fully understand your point and sincerely say it won't happen again...

**Comment by fnc12** [comment] 2021-04-25 12:26
select inside select is fully supported. Just imagine how would you write you subselect as a distinct select:
```sql
SELECT count(*) > 0 
    from Invoices ii 
    WHERE ii.fkey_claim = c.id_claim and ii.fkey_INSResponse = 1
```
then insert this code right into another query as a column.

**Comment by juandent** [comment] 2021-04-27 19:25
I am struggling with this piece of SQL or rather how it may be written in sqlite_orm
Would appreciate any help!

```SQL
select c.id_claim, (SELECT count(*) > 0 from Invoices ii WHERE ii.fkey_claim = c.id_claim and ii.fkey_INSResponse = 1), i.fkey_INSResponse = 1, i.number from Invoices i INNER JOIN Claims c on i.fkey_claim = c.id_claim
```

```C++
auto otherlines = storage.select(columns(alias_column<als_c>(&Claim::id), 
		storage.select(columns(greater_than(count<als_p>(), 0)),
			inner_join<als_m>(on(c(alias_column<als_m>(&Claim::id)) == alias_column<als_p>(&Invoice::fkey_claim))),
			where(c(alias_column<als_p>(&Invoice::fkey_INSResponse)) == 1))),
		inner_join<als_i>(on(c(alias_column<als_i>(&Invoice::fkey_claim)) == alias_column<als_c>(&Claim::id))));
```

**Comment by fnc12** [comment] 2021-04-28 08:36
now it must work in `dev` after fix for bool result for binary conditions. Please check it

**Comment by fnc12** [comment] 2021-04-30 06:06
@juandent is everything ok amigo?

**Comment by juandent** [comment] 2021-04-30 14:29
not quite amigo ... stilll don't know how to write the sql above.. can you help?

**Comment by juandent** [comment] 2021-04-30 23:57
I wrote the following as an attempt to produce the SQL in the first comment of this issue:

```C++
auto lines = storage.select(columns(alias_column<als_c>(&Claim::id),
		select(columns(greater_than(count<als_p>(), 0)),
			inner_join<als_m>(on(c(alias_column<als_m>(&Claim::id)) == alias_column<als_p>(&Invoice::fkey_claim))),
			where(c(alias_column<als_p>(&Invoice::fkey_INSResponse)) == 1))),
		inner_join<als_i>(on(c(alias_column<als_i>(&Invoice::fkey_claim)) == alias_column<als_c>(&Claim::id))));
```

This produces a hideous result in SQL:

```SQL
SELECT 'c'."id_claim", ( SELECT (COUNT(*) > ?) FROM 'Claims' m , 'Invoices' p  INNER JOIN  'Medications' 'm' ON ('m'."id_claim" = 'p'."fkey_claim") WHERE ( ('p'."fkey_INSResponse" = ?)) )  FROM 'Claims' c , 'Claims' m , 'Invoices' p  INNER JOIN  'Invoices' 'i' ON ('i'."fkey_claim" = 'c'."id_claim") 
```

So I have not yet solved this issue. Can you help please?

**Comment by juandent** [comment] 2021-04-30 23:58
Keep in mind that I have this aliases:

```C++
using als_c = alias_c<Claim>;
using als_p = alias_p<Patient>;
using als_d = alias_d<Doctor>;
using als_s = alias_s<Specialty>;
using als_m = alias_m<Medication>;
using als_i = alias_i<Invoice>;
using als_j = alias_j<INSResponse>;
using als_k = alias_k<INSResponseLine>;
using als_l = alias_l<Claim>;
using als_q = alias_q<Invoice>;
```

**Comment by juandent** [comment] 2021-04-30 23:59
all you need to solve this problem is contained in these 2 later comments above.... you don't need the schema

**Comment by juandent** [comment] 2021-05-01 05:51
This is a third attempt that compiles as an attempt to produce the SQL in the first comment of this issue:

```C++
auto lines = storage.select(columns(alias_column<als_c>(&Claim::id),
		select(columns(greater_than(count<als_i>(), 0)),
			inner_join<als_l>(on(c(alias_column<als_l>(&Claim::id)) == alias_column<als_i>(&Invoice::fkey_claim))),
			where(c(alias_column<als_i>(&Invoice::fkey_INSResponse)) == 1))),
		inner_join<als_i>(on(c(alias_column<als_i>(&Invoice::fkey_claim)) == alias_column<als_c>(&Claim::id))));
```

Produces this SQL closer to the goal:

```SQL
SELECT 'c'."id_claim", ( SELECT (COUNT(*) > ?) FROM 'Invoices' i  INNER JOIN  'Claims' 'l' ON ('l'."id_claim" = 'i'."fkey_claim") WHERE ( ('i'."fkey_INSResponse" = ?)) )  FROM 'Claims' c , 'Claims' l  INNER JOIN  'Invoices' 'i' ON ('i'."fkey_claim" = 'c'."id_claim") 
```

Can someone help out on this? I am stuck!

**Comment by fnc12** [comment] 2021-05-01 08:45
Here is your original query you want to write:
```sql
select c.id_claim, (
    SELECT count(*) > 0 
    from Invoices ii 
    WHERE ii.fkey_claim = c.id_claim and ii.fkey_INSResponse = 1
), i.fkey_INSResponse = 1, i.number 
from Invoices i 
INNER JOIN Claims c on i.fkey_claim = c.id_claim
```
Subselect does not contain INNER JOIN. Why did you add it to subselect?

**Comment by juandent** [comment] 2021-05-01 23:07
Sorry, forget that INNER JOIN .... 

The sqlite_orm is:

```C++
auto lines = storage.select(columns(alias_column<als_c>(&Claim::id),
		select(columns(greater_than(count<als_i>(), 0)),
				where(c(alias_column<als_i>(&Invoice::fkey_INSResponse)) == 1 && c(alias_column<als_i>(&Invoice::fkey_claim)) == alias_column<als_c>(&Claim::id)))),
		inner_join<als_i>(on(c(alias_column<als_i>(&Invoice::fkey_claim)) == alias_column<als_c>(&Claim::id))));
```

I believe there is a bug in the serialization of the SQL string. See how the first column of the select is from the Claim table and this table appears first in the FROM clause when it really should be Invoice (als_i)...

Here is the generated SQL:

```C++
SELECT 'c'."id_claim", ( SELECT (COUNT(*) > ?) FROM 'Claims' c , 'Invoices' i  WHERE ( (('i'."fkey_INSResponse" = ?) AND ('i'."fkey_claim" = 'c'."id_claim"))) )  FROM 'Claims' c  INNER JOIN  'Invoices' 'i' ON ('i'."fkey_claim" = 'c'."id_claim") 
```

The first ? will be substituted with 0, and the second with 1.

the embedded select should begin like so:

SELECT (COUNT(*) > 0) FROM Invoices i  WHERE .........

So I insist there is a bug in the serialization.

Regards,
Juan

**Comment by juandent** [comment] 2021-05-01 23:32
Forgive me I  posted the incorrect SQL string... indeed there is no INNER JOIN in the subselect. The problem  I keep getting is that the SQL generated for the subselect contains the table Claim which is incorrect. Also, and even worse, the ii.key_claim should be equal to the id_claim of the outer select (i.e. c.id_claim). That should produce a set of invoices belonging to a each particular claim.   We then count each claim's subset to see whether at least one of these invoices have key_INSResponse = 1

Is this possible in sqlite_orm? (or am I suggesting a new feature for you to say "Oh Man"? (haha)

Thanks for your time and look forward to your response with intensity!

**Comment by fnc12** [comment] 2021-05-02 03:00
everything must work out of box. Also I cannot see table `Claim` in subselect in the latest SQL query you posted:
```sql
SELECT 'c'."id_claim", ( 
    SELECT (COUNT(*) > ?) 
    FROM 'Invoices' i   //   <=== no Claim table
    INNER JOIN  'Claims' 'l' ON ('l'."id_claim" = 'i'."fkey_claim") 
    WHERE ( ('i'."fkey_INSResponse" = ?)) )  
FROM 'Claims' c , 'Claims' l  
INNER JOIN  'Invoices' 'i' ON ('i'."fkey_claim" = 'c'."id_claim") 
```
Please update your SQL string and then I can find what is wrong. Thanks

**Comment by juandent** [comment] 2021-05-02 13:33
Are you proposing this last SQL string to be the correct? (the one in your last comment)?

**Comment by juandent** [comment] 2021-05-02 14:20
Hi!

I am about to give up (look for another way to do this) but before I do, i want to ask you if you can show me what is wrong with this sqlite_orm query:

```C++
auto lines = storage.select(columns(alias_column<als_c>(&Claim::id),
		select(columns(greater_than(count<als_i>(), 0)),
				inner_join<als_c>(on(c(  alias_column<als_c>(&Claim::id )) == alias_column<als_i>(&Invoice::fkey_claim)))),
				where(c(alias_column<als_i>(&Invoice::fkey_INSResponse)) == 1 && c(alias_column<als_i>(&Invoice::fkey_claim)) == alias_column<als_c>(&Claim::id))),
		inner_join<als_i>(on(c(alias_column<als_i>(&Invoice::fkey_claim)) == alias_column<als_c>(&Claim::id))));
```

```C++
using als_c = alias_c<Claim>;
using als_p = alias_p<Patient>;
using als_d = alias_d<Doctor>;
using als_s = alias_s<Specialty>;
using als_m = alias_m<Medication>;
using als_i = alias_i<Invoice>;
using als_j = alias_j<INSResponse>;
using als_k = alias_k<INSResponseLine>;
using als_l = alias_l<Claim>;
using als_q = alias_q<Invoice>;
```


Please!

**Comment by fnc12** [comment] 2021-05-02 15:51
> Are you proposing this last SQL string to be the correct? (the one in your last comment)?

No. I am posting this to ask you to provide update SQL you expect. I just copypasted SQL from your last comment.

> When I said Claim table I meant Claims table (Claim is the struct) - I assumed you would understand that

It is clear and not needed to be explained thanks.

I cannot understand. You want to reproduce this SQL query (copy pasting from the first your comment):
```sql
select c.id_claim, (
    SELECT count(*) > 0 
    from Invoices ii 
    WHERE ii.fkey_claim = c.id_claim and ii.fkey_INSResponse = 1
), i.fkey_INSResponse = 1, i.number 
from Invoices i 
INNER JOIN Claims c on i.fkey_claim = c.id_claim
```
and you write code
```c++
auto lines = storage.select(columns(alias_column<als_c>(&Claim::id),
		select(columns(greater_than(count<als_i>(), 0)),
				inner_join<als_c>(on(c(  alias_column<als_c>(&Claim::id )) == alias_column<als_i>(&Invoice::fkey_claim)))),
				where(c(alias_column<als_i>(&Invoice::fkey_INSResponse)) == 1 && c(alias_column<als_i>(&Invoice::fkey_claim)) == alias_column<als_c>(&Claim::id))),
		inner_join<als_i>(on(c(alias_column<als_i>(&Invoice::fkey_claim)) == alias_column<als_c>(&Claim::id))));
```
Please pay attention to subselect in SQL:
```SQL
    SELECT count(*) > 0 
    from Invoices ii 
    WHERE ii.fkey_claim = c.id_claim and ii.fkey_INSResponse = 1
```
and subselect in C++:
```c++
select(columns(greater_than(count<als_i>(), 0)),
				inner_join<als_c>(on(c(  alias_column<als_c>(&Claim::id )) == alias_column<als_i>(&Invoice::fkey_claim)))),
```

You wrote subselect incorrectly: you skipped `where` and added `inner_join`. You need to make it correct and them everything will work. Not it looks like that you wrote incorrect query cause subselect works nice.

**Comment by juandent** [comment] 2021-05-02 15:52
Tried this - did not compile:

```C++
	auto otherlines = storage.select(columns(alias_column<als_c>(&Claim::id),
		select(columns(greater_than(count<als_i>(), 0)),
				where(c(alias_column<als_i>(&Invoice::fkey_INSResponse)) == 1),
				inner_join<als_c>(on(c(alias_column<als_c>(&Claim::id)) == alias_column<als_i>(&Invoice::fkey_claim)))),
		inner_join<als_i>(on(c(alias_column<als_i>(&Invoice::fkey_claim)) == alias_column<als_c>(&Claim::id)))));
```

Error:

Severity	Code	Description	Project	File	Line	Suppression State
Error	C2027	use of undefined type 'sqlite_orm::internal::column_result_t<St,sqlite_orm::internal::inner_join_t<als_i,sqlite_orm::internal::on_t<sqlite_orm::internal::is_equal_t<sqlite_orm::internal::alias_column_t<als_i,int Invoice::* >,sqlite_orm::internal::alias_column_t<als_c,int Claim::* >>>>,void>'

**Comment by fnc12** [comment] 2021-05-02 16:00
It happens cause you have incorrect parenthesis. You need to recreate it calm and correctly. Also why your SQL query has only one `INNER JOIN` and c++ has two `inner_join`?

Error reason is that the second `inner_join` is written inside `columns(...)` and this is incorrect.

**Comment by juandent** [comment] 2021-05-03 15:43
From scratch: The desired SQL string is:


```SQL
select c.id_claim, (
    SELECT count(*) > 0 
    from Invoices ii 
    WHERE ii.fkey_claim = c.id_claim and ii.fkey_INSResponse = 1
) 
from Invoices i 
INNER JOIN Claims c on i.fkey_claim = c.id_claim
```

but this cannot be written in sqlite_orm because there is no way to write the nested SQL because it writes the Claims table and makes it a Claims X Invoices 'dynamic' table  --- the generated SQL is


```SQL
SELECT 'c'."id_claim", ( SELECT (COUNT(*) > ?) FROM 'Claims' c , 'Invoices' q  WHERE ( (('q'."fkey_INSResponse" = ?) AND ('q'."fkey_claim" = 'c'."id_claim"))) )  FROM 'Claims' c , 'Invoices' q  INNER JOIN  'Invoices' 'i' ON ('i'."fkey_claim" = 'c'."id_claim") 
```

See why I needed to add an inner_join to the nested select?
But I tried it and it did not work either

**Comment by fnc12** [comment] 2021-05-03 18:35
Ok I see. The reason why generated SQL has `Claims` is that `sqlite_orm` needs to understand what tables must be written in `FROM` section. How it works? Storage iterates all over query (subquery in this case) and collects all tables mentioned. Subselect has `WHERE` section 
```sql
WHERE ii.fkey_claim = c.id_claim and ii.fkey_INSResponse = 1
``` 
with two tables mentioned: `c` and `ii` where `c` is `Claims` and `ii` is `Invoices`. And the bad thing is that this magic algorithm cannot understand whether you need to omit `Claims` table this time or not cause in both cases queries are valid.

Who can we do? My idea is to add explicit `FROM` feature. You'll add `from<als_q>` inside subselect's `select` function call right before `where` and I'll alter this magic algorithm to see whether query has explicit `FROM`. And if it does then algorithm will not try to guess tables list but will take list from `from<T>` call. If you do not need to specify `from` explicitly (just like you do in high level select) you may skip it and everything will work as before. What do you think?

**Comment by juandent** [comment] 2021-05-03 19:26
Beautiful solution!!! A great feature indeed!!!

How long do you think is going to take you to implement?

Thanks!! I knew I couldn't be that dumb!

Regards and praise to keep this library growing!!!

**Comment by fnc12** [comment] 2021-05-03 19:28
@juandent let me start it tomorrow. I must not take long. Thank you for your help.

**Comment by juandent** [comment] 2021-05-03 19:46
You are very welcome!!!

**Comment by juandent** [comment] 2021-05-12 16:06
Hi @fnc12 !
Any progress?

Regards,
Juan

**Comment by fnc12** [comment] 2021-05-12 16:31
@juandent in progress

**Comment by fnc12** [comment] 2021-05-13 13:41
@juandent PR is here https://github.com/fnc12/sqlite_orm/pull/725

**Comment by fnc12** [comment] 2021-05-13 16:17
@juandent merged into `dev`. Please check it out

**Comment by juandent** [comment] 2021-05-13 21:08
Hello @fnc12 
Very fast response man!! I have a doubt:

This SQL:

```SQL
select c.id_claim, (
    SELECT count(*) > 0 
    from Invoices ii 
    WHERE ii.fkey_claim = c.id_claim and ii.fkey_INSResponse = 1
), i.fkey_INSResponse = 1, i.number 
from Invoices i 
INNER JOIN Claims c on i.fkey_claim = c.id_claim
```

written in sqlite_orm as:

```C++
	auto otherlines = storage.select(columns(alias_column<als_c>(&Claim::id),
		select(columns(greater_than(count<als_q>(), 0)), from<als_q>(),
			where(c(alias_column<als_q>(&Invoice::fkey_INSResponse)) == 1 && c(alias_column<als_q>(&Invoice::fkey_claim)) == alias_column<als_c>(&Claim::id)))),
		inner_join<als_i>(on(c(alias_column<als_i>(&Invoice::fkey_claim)) == alias_column<als_c>(&Claim::id))));
```

is serialized incorrectly as:


```SQL
SELECT 'c'."id_claim", 
(SELECT (COUNT(*) > ?) FROM 'Invoices' 'q' WHERE ( (('q'."fkey_INSResponse" = ?) AND ('q'."fkey_claim" = 'c'."id_claim"))) ) 
FROM 'Claims' c , 'Invoices' q  INNER JOIN  'Invoices' 'i' ON ('i'."fkey_claim" = 'c'."id_claim") 
```
So I am going to have to do the FROM clause for the outer SQL manually. Do you consider this a bug?

**Comment by juandent** [comment] 2021-05-13 22:31
I have changed the sqlite_orm code and it produces correct SQL  code (code that runs perfectly in DBBrowser for SQLITE) but that does not run correctly in sqlite_orm. There is a bug in the placeholders. Let me explain fully:

The C++ code is:
```C++
auto lines = storage.select(columns(alias_column<als_c>(&Claim::id),
		select(columns(greater_than(count<als_q>(), 0)), from<als_q>(),
			where(c(alias_column<als_q>(&Invoice::fkey_INSResponse)) == 1 && c(alias_column<als_q>(&Invoice::fkey_claim)) == alias_column<als_c>(&Claim::id)))),
		from<als_i>(), inner_join<als_c>(on(c(alias_column<als_i>(&Invoice::fkey_claim)) == alias_column<als_c>(&Claim::id))), group_by(alias_column<als_c>(&Claim::id)));
```

becomes this SQL:
```SQL
SELECT 'c'."id_claim", 
(SELECT (COUNT(*) > ?) FROM 'Invoices' 'q' WHERE ( (('q'."fkey_INSResponse" = ?) AND ('q'."fkey_claim" = 'c'."id_claim"))) ) 
FROM 'Claims' c , 'Invoices' q  INNER JOIN  'Invoices' 'i' ON ('i'."fkey_claim" = 'c'."id_claim") 
```

The bug comes in the placeholders '?' These are not substituted correctly. I end up with every row showing a 1 for the second column as if each invoice subset for each claim has at least one row for which fkey_INSResponse = 1 and this is not true - I can look at the invoices and they do not contain the number 1 in every invoice subset for each claim.

The output is


1  	1
2      1
3       1
4      1
5      1
.......


Thus, everything works except for the step where placeholders are filled up!!



How can I share this code with you? So that you can verify it yourself ?

Regards,
Juan Dent

**Comment by fnc12** [comment] 2021-05-14 02:21
@juandent paste diff here or sent it to me to fnc12@me.com

**Comment by juandent** [comment] 2021-05-14 23:43
Sent code to fnc12@me.com... please let me know when you receive it

**Comment by fnc12** [comment] 2021-05-15 08:46
@juandent I received your code but I can not understand what is wrong now. You provided SQL and it looks nice cause subselect now has only one table in `FROM` expression not two as it was before:
```sql
SELECT 'c'."id_claim", (
    SELECT (COUNT(*) > ?) 
    FROM 'Invoices' 'q' 
    WHERE ( (('q'."fkey_INSResponse" = ?) AND ('q'."fkey_claim" = 'c'."id_claim"))) ) 
FROM 'Claims' c , 'Invoices' q  INNER JOIN  'Invoices' 'i' ON ('i'."fkey_claim" = 'c'."id_claim") 
```
What SQL do you expect instead?

**Comment by juandent** [comment] 2021-05-15 14:10
The SQL is correct but it is not correctly executed 
The placeholders ? Are correctly substituted 

The proof is we have two claims one with one invoice with fkey_INSResponse 
= 1 and the other with fkey_INSResponse = 2

Thus one claim should return true and the other false

But both return true!

Am I clear?

Regards
Juan Dent

**Comment by juandent** [comment] 2021-05-15 14:13
CORRECTION: 

> The placeholders ? Are INCORRECTLY substituted

**Comment by juandent** [comment] 2021-05-16 18:19
Hi @fnc12 have you able to reproduce the bug? Is data.cpp clear enough?

rewards,
Juan Dent

**Comment by fnc12** [comment] 2021-05-17 05:28
@juandent in progress right now

**Comment by fnc12** [comment] 2021-05-17 06:57
@juandent yes some bug exists in `tuple` extraction. IDK yet the clue but I know for sure how to fix your case. You have redundant `columns` call inside subselect. Please replace `columns(greater_than(count<als_q>(), 0))` with `greater_than(count<als_q>(), 0)`.

**Comment by juandent** [comment] 2021-05-18 14:05
Yes it worked like a charm!! Thanks 🙏

**Comment by fnc12** [comment] 2021-07-01 05:44
@juandent is the issue actual?

**Comment by fnc12** [comment] 2021-07-26 14:04
I am closing this. If there is something left please reopen it

**Closed** 2021-08-02 06:30 UTC
Labels: feature, question, verify
