### ISSUE TITLE
Lattest version build error

### ISSUE THREAD

**Issue by mmuruev** [fnc12/sqlite_orm#93] opened 2018-02-06 15:04 UTC
I have an old version maybe something about just started lib ver. But it has weird issue with 'long' fields, just return "" string instead of filed name which caused SQL error. Trying to upgrade for latest and got build error. 

```c++
> /sqlite_orm.h:4178:27: error: no matching function for call to ‘std::__cxx11::basic_string<char>::basic_string(sqlite_orm::internal::column_t<Counter, unsigned int>&)’
                     ss << static_cast<std::string>(v) << ' ';
                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by fnc12** [comment] 2018-02-06 16:54
please give me your project code - I need to test it on my machine

**Comment by fnc12** [comment] 2018-02-07 17:57
@mmuruev bump

**Comment by fnc12** [comment] 2018-02-27 16:13
cannot reproduce. Closing

**Closed by fnc12** 2018-02-27 16:13 UTC
Labels: bug

**Comment by mmuruev** [comment] 2018-03-11 14:13
Sorry for delay. Use this only for my home project. So I've got lattes version the ORM and it compiled just fine. I don't know what it was. I belive can be related to issue with create schema, which I found out latter so probably first version just do not had such checks, I compiled but  not created right tables. Now it's definitely better. Good Job !
