### ISSUE TITLE
Binding doesn't work with getter & setter

### ISSUE THREAD

**Issue by pminiszewski** [fnc12/sqlite_orm#1202] opened 2023-08-25 13:40 UTC
Hello,
While experimenting with sqlite_orm and custom type bindings I found that bindings do not support using getters and setters.
Consider example below: 
```cpp
#include "lib/sqlite_orm.h"

struct NestedType
{
  int some_value_;
};
struct TypeB
{ 
  void set_id(int _id) { id_ = _id;}
  int get_id() { return id_;}

  void set_value(const NestedType& _a) { a_ = _a;}
  NestedType get_value() { return a_;}

  NestedType a_;
  private:
  int id_;
};

namespace sqlite_orm
{
  template<>
  struct type_printer<NestedType> : public integer_printer {};

  template<> 
  struct statement_binder<NestedType>
  {
    int bind(sqlite3_stmt* _stmt, int _index, const NestedType& _value)
    {
      return sqlite3_bind_int(_stmt, _index, _value.some_value_);
    }
  };

  template<>
  struct field_printer<NestedType>
  {
    std::string operator()(const NestedType& _val) const 
    {
      return std::to_string(_val.some_value_);
    }
  };
  
  template<>
  struct row_extractor<NestedType>
  {
    NestedType extract(sqlite3_stmt* _stmt, int _index)
    {
      auto val = sqlite3_column_int(_stmt, _index);
      NestedType ret;
      ret.some_value_ = val;
      return ret;
    }
  };
}

void test()
{
  using namespace sqlite_orm;

  auto test = make_storage({},

      make_table("my_table",
          make_column("id", &TypeB::get_id, &TypeB::set_id, unique(), primary_key())
          ,make_column("a", &TypeB::get_value, &TypeB::set_value) //ERROR; doesn't compile
          //,make_column("a", &TypeB::a_) // Works fine
        )
    );
    test.sync_schema();

    TypeB x;
    x.set_id(123);
    x.set_value({3});
    test.insert<TypeB>(x);
}
```

If I try to map property through getter and setter, the compilation will fail. Same code compiles fine if I make property public and make column out of it directly (see `make_table`). Unfortunately I'm using protobuf types which do not expose any members directly :(

**Comment by fnc12** [comment] 2023-10-07 14:46
Hi @pminiszewski . I am able to reproduce it. Thanks for reporting. Trying to fix

**Comment by fnc12** [comment] 2023-10-07 14:52
it compiles well if getters are right const. Your getters in `TypeB` are not right const. Replace `NestedType get_value() { return a_;}` with `NestedType get_value() const { return a_;}` to make it work. It is important detail cause when we call insert we pass the object as a const ref to a lot of subfunctions to make the storage work as intended. Those functions don't work with non-const member function pointers during getting value within `insert` call cause they are not intended to change the object

**Comment by fnc12** [comment] 2023-10-07 14:52
I am closing it cause it is not a bug and it doesn't require any work to commit into repo. If you have something else please feel free to reopen it

**Closed by fnc12** 2023-10-07 14:52 UTC
Labels: notabug
