### ISSUE TITLE
add column sync_schema will recreate table 

### ISSUE THREAD

**Issue by SevenFantastic** [fnc12/sqlite_orm#1261] opened 2024-01-09 06:52 UTC
in my table create sql, primary key just set pk and autoincremnet.
![image](https://github.com/fnc12/sqlite_orm/assets/20679462/5531c00d-00b4-42a4-bd88-a055687c03db)
when i use sync_schema to add new column.
table droped and recreated.
i debuged the calculate_remove_add_columns, catch the problem with the pk column.
![image](https://github.com/fnc12/sqlite_orm/assets/20679462/3f2888d0-424b-47c1-b04b-60965424c3e6)
the storage pk column info notnull is true
![image](https://github.com/fnc12/sqlite_orm/assets/20679462/cf3e27e3-0334-4eb0-9f7a-7eb8cbfe30e6)
the db pk column info notnull is false 
it makes next result to the drop&recreated table.

i make sure the pk column of db struct info not null is false.
![image](https://github.com/fnc12/sqlite_orm/assets/20679462/32e397c1-c30f-4fe2-be33-1cb5c7a8beb8)

but older db file cant be compatible this problem.

i just modified the code, set the db pk col to not null. 
![image](https://github.com/fnc12/sqlite_orm/assets/20679462/3acfd92f-fa82-45be-81b7-096b26337d4e)
if (dbColumnInfo.pk) { dbColumnInfo.notnull = true; }

**Comment by fnc12** [comment] 2024-01-09 08:21
please show me your C++ struct mapped to the storage

**Comment by SevenFantastic** [comment] 2024-01-09 08:28
![image](https://github.com/fnc12/sqlite_orm/assets/20679462/f85d0dc1-9127-4308-9590-8f8230817022)
![image](https://github.com/fnc12/sqlite_orm/assets/20679462/3eacff12-4c50-40b3-a402-6d56f5a77a52)
this is struct and mapped code.

**Comment by fnc12** [comment] 2024-01-09 08:31
`&Task::id` can't be `NULL` cause it is `int` - `int` can't be `NULL`. That's why `sync_schema` tries to make `task_id` column non-nullable - it is correct behavior. If you still want to call `sync_schema` and avoid table recreating replace `int id` with something nullable like `std::optional<int> id`

**Comment by SevenFantastic** [comment] 2024-01-09 08:32
In SQLite, it is possible to create a primary key column without explicitly declaring it as NOT NULL. However, in other databases, defining a column as a primary key automatically sets it to NOT NULL.

**Comment by SevenFantastic** [comment] 2024-01-09 08:35
i used msvc2017. it not support std::optional very well.

**Comment by fnc12** [comment] 2024-01-09 08:42
> In SQLite, it is possible to create a primary key column without explicitly declaring it as NOT NULL. However, in other databases, defining a column as a primary key automatically sets it to NOT NULL.

If `PRAGMA table_info` returns `notnull` as `0` then it can be NULL. This is how the engine works not `sqlite_orm`.

> i used msvc2017. it not support std::optional very well.

Ok you can try the other way: add migration code which will extract all records from `task` table, call `sync_schema` and put the data back again. You can do it manually with a lot of pain or you can purchase `sqlite_orm_plus` which is `sqlite_orm` with migrations API added

**Comment by SevenFantastic** [comment] 2024-01-09 08:58
Okay, the sync_schema(true) function will recreate the table and re-import the data into the database. 
However, I've noticed that in the table_info, the primary key (PK) column has its 'notnull' attribute set to 0. 
This is quite confusing. 
I believe that not check a 'notnull' constraint on the PK column could be a viable solution.

**Comment by fnc12** [comment] 2024-01-09 09:04
> I believe that not check a 'notnull' constraint on the PK column could be a viable solution.

What do you mean?

**Comment by fnc12** [comment] 2024-01-09 10:11
@SevenFantastic `notnull` is defined by SQLite. There is no reason to override it in `sqlite_orm`

**Comment by SevenFantastic** [comment] 2024-01-09 10:25
This is indeed correct and represents a specific issue with SQLite. 
The solution is to make the SQL creation process more sensitive and to use it with increased caution.
but the most compatible migration strategy often involves adding columns rather than recreating tables.

**Comment by fnc12** [comment] 2024-01-09 10:27
anyway it is not a bug. Closing

**Closed by fnc12** 2024-01-09 10:27 UTC
Labels: investigation
