### ISSUE TITLE
Large insert_range can hit SQLITE_MAX_VARIABLE_NUMBER limit

### ISSUE THREAD

**Issue by TimSC** [fnc12/sqlite_orm#144] opened 2018-04-21 23:08 UTC
A large insert_range can hit SQLITE_MAX_VARIABLE_NUMBER limit. This can be as low as 999.

If the limit is reached, the prepare function fails with "SQL Logic error or missing database".

**Comment by fnc12** [comment] 2018-04-22 04:28
what behavior do you expect instead?

**Comment by TimSC** [comment] 2018-04-22 14:26
I'd like a way to reliably call insert_range. 

Either it could split the insert_range data into manageable chunks or fail with a more helpful error message. I'm not sure which is best.

**Comment by fnc12** [comment] 2018-04-23 17:46
@TimSC can you give me a code to reproduce the issue?

**Comment by TimSC** [comment] 2018-04-24 08:46
@fnc12 If you grab tests.cpp from my PR branch and run it with the original master sqlite_orm.h, you should be able to reproduce it.

**Comment by fnc12** [comment] 2018-05-12 05:48
@TimSC I'm unable to reproduce it. I've inserted up to 10k entities with `insert_range` and it worked. What number of entities crash your app?

**Comment by TimSC** [comment] 2018-05-12 08:57
@fnc12 The value of SQLITE_LIMIT_VARIABLE_NUMBER depends on how sqlite is compiled. On my platform it is 250000. In my version of insert_range, what is the value of max_variables for you?

**Comment by fnc12** [comment] 2018-05-12 09:02
How to get this value? `insertLimit = sqlite3_limit(db, SQLITE_LIMIT_COMPOUND_SELECT, -1);` returns 0

**Comment by fnc12** [comment] 2018-05-12 09:47
@TimSC 
1) I don't understand these two lines. What every lines does? Why do you put `100` as a third argument in the first line? Second line looks like a getter but you don't retain returned value
2) This issue's solution assumes that `insert_range` and `replace_range` may perform > 1 query. This is illogical cause main lib advantage is clarity that guarantees that one function call performs a single sql query. Maybe it is more logical to add interface for setting and getting max variables to a storage class?

**Comment by TimSC** [comment] 2018-05-12 13:58
The API for sqlite is rather strange. The first line gets and sets the value. The set value is arbitrary since we change it to the default (-1) on the second line. This approach was based on this comment https://github.com/jgallagher/rusqlite/issues/220#issuecomment-277731280 Perhaps a better approach would be:

            int max_variables = sqlite3_limit(connection->get_db(), SQLITE_LIMIT_VARIABLE_NUMBER, -1);
            sqlite3_limit(connection->get_db(), SQLITE_LIMIT_VARIABLE_NUMBER, max_variables);

This restores the value to whatever it was before the function call.

For question 2, yes it uses multiple SQL queries. I'm not sure what the best approach - my prefered approach is in the pull request, but I guess it's your decision!

**Comment by fnc12** [comment] 2018-05-19 11:36
@TimSC please checkout out the latest PR in the `dev` branch (I've also merged it in `master` branch accidentally). Bad news: you cannot increase `variable_number` limit without sqlite recompilation so all you can do is to get the limit number and divide your container by this value.

**Comment by fnc12** [comment] 2018-05-27 16:53
@TimSC I think that maybe it is better to add `safe_replace_range` and `safe_insert_range` to `storage_t` function that would split container insertion into several queries if required

**Comment by TimSC** [comment] 2018-05-27 18:46
@fnc12 I will have a look at that branch... eventually.

Perhaps have an option argument like "safe=false" in insert_range?

**Comment by fnc12** [comment] 2018-05-27 18:54
Oh, optional argument is even better. 

Yes, multiple insert would work within a transaction

**Comment by fnc12** [comment] 2018-05-29 20:26
what's your compiler's output?

**Comment by TimSC** [comment] 2018-05-29 20:33
I opened #147

**Comment by fnc12** [comment] 2018-10-08 12:04
@TimSC #147 is fixed, all limits are available with `sqlite_orm` API. Is the issue actual?

**Comment by TimSC** [comment] 2018-10-08 15:12
@fnc12 I'd prefer safe versions of insert and update, or using an optional argument to make an insert or update safe. Users might still be caught by surprise by sqlite limits. Advanced users will check the limits of course.

Are we going with just having the limits available or having safe insert/update?

**Comment by fnc12** [comment] 2018-10-08 15:13
looks like safe insert/replace is better. I'll think about it and add it probably. Anyway I'll leave a feedback here soon

**Comment by fnc12** [comment] 2018-10-21 17:30
@TimSC if we are going to add safe insert/replace range then how we gonna name these functions? `safe_insert` doesn't tell me why it is safe cause less people know about sqlite insert limits

**Comment by fnc12** [comment] 2018-10-23 13:41
default as safe looks good but it breaks the `one function = one query` rule. Also `std::vector::operator[]` doesn't check out of bounds case but `std::vector::at` does cause `operator[]` tries to implement pure C behavior in back compatibility style.
The best idea IMHO would be add optional argument `safe = false` in `insert_range` and `replace_range` functions.

**Comment by fnc12** [comment] 2020-12-18 20:00
@TimSC you know I think we don't have to create such API cause the main rule if this lib is one function call per one query. Exception is `sync_schema`. And this functionality can be performed manually right now. So let's leave it as is.

**Closed by fnc12** 2020-12-18 20:00 UTC
Labels: enhancement
