### ISSUE TITLE
Question how pass column as parameter to a function?

### ISSUE THREAD

**Issue by WXIN** [fnc12/sqlite_orm#373] opened 2019-09-09 22:06 UTC
```c++
struct EteStatistics
{
    unsigned int region_id;
    unsigned int timestamp;
    double cum_vehs_discharged;
    float pct_evacuated = -1;
};
```
I have a function that intends to take columns as parameters
```c++
template<typename Ta, typename Tv, typename Tp>
void calculatePercentile(Storage &a_storage, Ta a_agg_col, Tv a_value_col, Tp a_pct_col)
{
    using namespace sqlite_orm;
    auto l_max_table = a_storage.select(columns(a_agg_col, max(a_value_col)),
        group_by(a_agg_col));
   
    for (auto &row : l_max_table) {
        a_storage.update_all(
            set(c(a_pct_col) = c(a_value_col) / *std::get<1>(row)),
            where(c(a_agg_col) == std::get<0>(row))
        );
    }
}
```
When I do the following call, it doesn't work
`   calculatePercentile(a_storage, &EteStatistics::region_id, 
        &EteStatistics::cum_vehs_discharged, &EteStatistics::pct_evacuated)`

Any advice?  Thank you.

**Comment by WXIN** [comment] 2019-09-10 02:46
It seems after I added "perfect" forwarding, it works:

template<typename Ta, typename Tv, typename Tp>
void **calculatePercentile**(Storage &a_storage, Ta &&a_agg_col, Tv &&a_value_col, Tp &&a_pct_col)
{
    using namespace sqlite_orm;
    auto l_max_table = a_storage.select(columns(std::forward<Ta>(a_agg_col), max(std::forward<Tv>(a_value_col))),
        group_by(a_agg_col));
   
    for (auto &row : l_max_table) {
        a_storage.update_all(
            set(c(a_pct_col) = c(a_value_col) / *std::get<1>(row)),
            where(c(a_agg_col) == std::get<0>(row))
        );
    }
}

**Comment by fnc12** [comment] 2019-09-10 09:50
If something doesn't work please provide more details about "how do you expect it to work and what you get instead". Also if the issue isn't actual already please close it. Thanks

**Closed** 2019-09-10 10:32 UTC
