### ISSUE TITLE
Cannot use aggregate functions like count, sum, etc...

### ISSUE THREAD

**Issue by Falgu9** [fnc12/sqlite_orm#1187] opened 2023-05-26 13:39 UTC
Here is my code : tests.cpp
```c++
#include "gtest/gtest.h"
#include "gmock/gmock.h"

#include <iostream>

#include "sqlite_orm/sqlite_orm.h"

TEST(TestM, TestCount)
{
    using namespace sqlite_orm;
    struct M
    {
        int id;
        int hard_id;
    };
    auto storage = make_storage("",
                                make_table("M",
                                           make_column("ID", &M::id, primary_key().autoincrement()),
                                           make_column("HW_ID", &M::hard_id)));
    storage.sync_schema();
    std::cout << storage.count<M>() << std::endl;
}
``` 

My prompt : 

```c++
In file included from ../sqlite_orm/not_single_header_include/sqlite_orm/sqlite_orm.h:25,
                 from tests/tests.cpp:9:
../sqlite_orm/not_single_header_include/sqlite_orm/../../dev/statement_binder.h: In instantiation of ‘void sqlite_orm::internal::conditional_binder::operator()(const T&) [with T = sqlite_orm::internal::count_asterisk_t<TestModulator_TestCount_Test::TestBody()::M>; typename std::enable_if<std::integral_constant<bool, is_bindable_v<T> >::value, bool>::type <anonymous> = 1]’:
../sqlite_orm/not_single_header_include/sqlite_orm/../../dev/ast_iterator.h:53:23:   required from ‘void sqlite_orm::internal::ast_iterator<T, SFINAE>::operator()(const T&, L&) const [with L = sqlite_orm::internal::conditional_binder; T = sqlite_orm::internal::count_asterisk_t<TestModulator_TestCount_Test::TestBody()::M>; SFINAE = void]’
../sqlite_orm/not_single_header_include/sqlite_orm/../../dev/ast_iterator.h:63:21:   required from ‘void sqlite_orm::internal::iterate_ast(const T&, L&&) [with T = sqlite_orm::internal::count_asterisk_t<TestModulator_TestCount_Test::TestBody()::M>; L = sqlite_orm::internal::conditional_binder&]’
../sqlite_orm/not_single_header_include/sqlite_orm/../../dev/ast_iterator.h:251:28:   required from ‘void sqlite_orm::internal::ast_iterator<sqlite_orm::internal::select_t<T, Args ...>, void>::operator()(const node_type&, L&) const [with L = sqlite_orm::internal::conditional_binder; T = sqlite_orm::internal::count_asterisk_t<TestModulator_TestCount_Test::TestBody()::M>; Args = {}; sqlite_orm::internal::ast_iterator<sqlite_orm::internal::select_t<T, Args ...>, void>::node_type = sqlite_orm::internal::select_t<sqlite_orm::internal::count_asterisk_t<TestModulator_TestCount_Test::TestBody()::M> >]’
../sqlite_orm/not_single_header_include/sqlite_orm/../../dev/ast_iterator.h:63:21:   required from ‘void sqlite_orm::internal::iterate_ast(const T&, L&&) [with T = sqlite_orm::internal::select_t<sqlite_orm::internal::count_asterisk_t<TestModulator_TestCount_Test::TestBody()::M> >; L = sqlite_orm::internal::conditional_binder]’
../sqlite_orm/not_single_header_include/sqlite_orm/../../dev/storage.h:1360:28:   required from ‘std::vector<R> sqlite_orm::internal::storage_t<DBO>::execute(const sqlite_orm::internal::prepared_statement_t<sqlite_orm::internal::select_t<T, Args ...> >&) [with T = sqlite_orm::internal::count_asterisk_t<TestModulator_TestCount_Test::TestBody()::M>; Args = {}; R = int; DBO = {sqlite_orm::internal::table_t<TestModulator_TestCount_Test::TestBody()::M, false, sqlite_orm::internal::column_t<int TestModulator_TestCount_Test::TestBody()::M::*, sqlite_orm::internal::empty_setter, sqlite_orm::internal::primary_key_with_autoincrement<sqlite_orm::internal::primary_key_t<> > >, sqlite_orm::internal::column_t<int TestModulator_TestCount_Test::TestBody()::M::*, sqlite_orm::internal::empty_setter> >}]’
../sqlite_orm/not_single_header_include/sqlite_orm/../../dev/storage.h:575:47:   required from ‘std::vector<R> sqlite_orm::internal::storage_t<DBO>::select(T, Args ...) [with T = sqlite_orm::internal::count_asterisk_t<TestModulator_TestCount_Test::TestBody()::M>; Args = {}; R = int; DBO = {sqlite_orm::internal::table_t<TestModulator_TestCount_Test::TestBody()::M, false, sqlite_orm::internal::column_t<int TestModulator_TestCount_Test::TestBody()::M::*, sqlite_orm::internal::empty_setter, sqlite_orm::internal::primary_key_with_autoincrement<sqlite_orm::internal::primary_key_t<> > >, sqlite_orm::internal::column_t<int TestModulator_TestCount_Test::TestBody()::M::*, sqlite_orm::internal::empty_setter> >}]’
../sqlite_orm/not_single_header_include/sqlite_orm/../../dev/storage.h:413:22:   required from ‘int sqlite_orm::internal::storage_t<DBO>::count(Args&& ...) [with O = TestModulator_TestCount_Test::TestBody()::M; Args = {}; R = TestModulator_TestCount_Test::TestBody()::M; DBO = {sqlite_orm::internal::table_t<TestModulator_TestCount_Test::TestBody()::M, false, sqlite_orm::internal::column_t<int TestModulator_TestCount_Test::TestBody()::M::*, sqlite_orm::internal::empty_setter, sqlite_orm::internal::primary_key_with_autoincrement<sqlite_orm::internal::primary_key_t<> > >, sqlite_orm::internal::column_t<int TestModulator_TestCount_Test::TestBody()::M::*, sqlite_orm::internal::empty_setter> >}]’
tests/tests.cpp:24:35:   required from here
../sqlite_orm/not_single_header_include/sqlite_orm/../../dev/statement_binder.h:286:48: error: invalid use of incomplete type ‘struct sqlite_orm::statement_binder<sqlite_orm::internal::count_asterisk_t<TestModulator_TestCount_Test::TestBody()::M>, void>’
                 int rc = statement_binder<T>{}.bind(this->stmt, this->index++, t);
                          ~~~~~~~~~~~~~~~~~~~~~~^~~~
../sqlite_orm/not_single_header_include/sqlite_orm/../../dev/statement_binder.h:30:12: note: declaration of ‘struct sqlite_orm::statement_binder<sqlite_orm::internal::count_asterisk_t<TestModulator_TestCount_Test::TestBody()::M>, void>’
     struct statement_binder;
            ^~~~~~~~~~~~~~~~
In file included from ../sqlite_orm/not_single_header_include/sqlite_orm/../../dev/storage.h:48,
                 from ../sqlite_orm/not_single_header_include/sqlite_orm/sqlite_orm.h:33,
                 from tests/tests.cpp:9:
../sqlite_orm/not_single_header_include/sqlite_orm/../../dev/statement_serializer.h: In instantiation of ‘std::__cxx11::string sqlite_orm::internal::serialize(const T&, const sqlite_orm::internal::serializer_context<DBOs>&) [with T = sqlite_orm::internal::count_asterisk_t<TestModulator_TestCount_Test::TestBody()::M>; DBOs = std::tuple<sqlite_orm::internal::table_t<TestModulator_TestCount_Test::TestBody()::M, false, sqlite_orm::internal::column_t<int TestModulator_TestCount_Test::TestBody()::M::*, sqlite_orm::internal::empty_setter, sqlite_orm::internal::primary_key_with_autoincrement<sqlite_orm::internal::primary_key_t<> > >, sqlite_orm::internal::column_t<int TestModulator_TestCount_Test::TestBody()::M::*, sqlite_orm::internal::empty_setter> > >; std::__cxx11::string = std::__cxx11::basic_string<char>]’:
../sqlite_orm/not_single_header_include/sqlite_orm/../../dev/column_names_getter.h:70:50:   required from ‘std::vector<std::__cxx11::basic_string<char> >& sqlite_orm::internal::column_names_getter::operator()(const E&, const Ctx&) [with E = sqlite_orm::internal::count_asterisk_t<TestModulator_TestCount_Test::TestBody()::M>; Ctx = sqlite_orm::internal::serializer_context<std::tuple<sqlite_orm::internal::table_t<TestModulator_TestCount_Test::TestBody()::M, false, sqlite_orm::internal::column_t<int TestModulator_TestCount_Test::TestBody()::M::*, sqlite_orm::internal::empty_setter, sqlite_orm::internal::primary_key_with_autoincrement<sqlite_orm::internal::primary_key_t<> > >, sqlite_orm::internal::column_t<int TestModulator_TestCount_Test::TestBody()::M::*, sqlite_orm::internal::empty_setter> > > >]’
../sqlite_orm/not_single_header_include/sqlite_orm/../../dev/column_names_getter.h:115:30:   required from ‘std::vector<std::__cxx11::basic_string<char> > sqlite_orm::internal::get_column_names(const T&, const Ctx&) [with T = sqlite_orm::internal::count_asterisk_t<TestModulator_TestCount_Test::TestBody()::M>; Ctx = sqlite_orm::internal::serializer_context<std::tuple<sqlite_orm::internal::table_t<TestModulator_TestCount_Test::TestBody()::M, false, sqlite_orm::internal::column_t<int TestModulator_TestCount_Test::TestBody()::M::*, sqlite_orm::internal::empty_setter, sqlite_orm::internal::primary_key_with_autoincrement<sqlite_orm::internal::primary_key_t<> > >, sqlite_orm::internal::column_t<int TestModulator_TestCount_Test::TestBody()::M::*, sqlite_orm::internal::empty_setter> > > >]’
../sqlite_orm/not_single_header_include/sqlite_orm/../../dev/statement_serializer.h:1504:60:   required from ‘std::__cxx11::string sqlite_orm::internal::statement_serializer<sqlite_orm::internal::select_t<T, Args ...>, void>::operator()(const statement_type&, Ctx) const [with Ctx = sqlite_orm::internal::serializer_context<std::tuple<sqlite_orm::internal::table_t<TestModulator_TestCount_Test::TestBody()::M, false, sqlite_orm::internal::column_t<int TestModulator_TestCount_Test::TestBody()::M::*, sqlite_orm::internal::empty_setter, sqlite_orm::internal::primary_key_with_autoincrement<sqlite_orm::internal::primary_key_t<> > >, sqlite_orm::internal::column_t<int TestModulator_TestCount_Test::TestBody()::M::*, sqlite_orm::internal::empty_setter> > > >; T = sqlite_orm::internal::count_asterisk_t<TestModulator_TestCount_Test::TestBody()::M>; Args = {}; std::__cxx11::string = std::__cxx11::basic_string<char>; sqlite_orm::internal::statement_serializer<sqlite_orm::internal::select_t<T, Args ...>, void>::statement_type = sqlite_orm::internal::select_t<sqlite_orm::internal::count_asterisk_t<TestModulator_TestCount_Test::TestBody()::M> >]’
../sqlite_orm/not_single_header_include/sqlite_orm/../../dev/statement_serializer.h:57:30:   required from ‘std::__cxx11::string sqlite_orm::internal::serialize(const T&, const sqlite_orm::internal::serializer_context<DBOs>&) [with T = sqlite_orm::internal::select_t<sqlite_orm::internal::count_asterisk_t<TestModulator_TestCount_Test::TestBody()::M> >; DBOs = std::tuple<sqlite_orm::internal::table_t<TestModulator_TestCount_Test::TestBody()::M, false, sqlite_orm::internal::column_t<int TestModulator_TestCount_Test::TestBody()::M::*, sqlite_orm::internal::empty_setter, sqlite_orm::internal::primary_key_with_autoincrement<sqlite_orm::internal::primary_key_t<> > >, sqlite_orm::internal::column_t<int TestModulator_TestCount_Test::TestBody()::M::*, sqlite_orm::internal::empty_setter> > >; std::__cxx11::string = std::__cxx11::basic_string<char>]’
../sqlite_orm/not_single_header_include/sqlite_orm/../../dev/storage.h:953:71:   required from ‘sqlite_orm::internal::prepared_statement_t<S> sqlite_orm::internal::storage_t<DBO>::prepare_impl(S) [with S = sqlite_orm::internal::select_t<sqlite_orm::internal::count_asterisk_t<TestModulator_TestCount_Test::TestBody()::M> >; DBO = {sqlite_orm::internal::table_t<TestModulator_TestCount_Test::TestBody()::M, false, sqlite_orm::internal::column_t<int TestModulator_TestCount_Test::TestBody()::M::*, sqlite_orm::internal::empty_setter, sqlite_orm::internal::primary_key_with_autoincrement<sqlite_orm::internal::primary_key_t<> > >, sqlite_orm::internal::column_t<int TestModulator_TestCount_Test::TestBody()::M::*, sqlite_orm::internal::empty_setter> >}]’
../sqlite_orm/not_single_header_include/sqlite_orm/../../dev/storage.h:1015:58:   required from ‘sqlite_orm::internal::prepared_statement_t<sqlite_orm::internal::select_t<T, Args ...> > sqlite_orm::internal::storage_t<DBO>::prepare(sqlite_orm::internal::select_t<T, Args ...>) [with T = sqlite_orm::internal::count_asterisk_t<TestModulator_TestCount_Test::TestBody()::M>; Args = {}; DBO = {sqlite_orm::internal::table_t<TestModulator_TestCount_Test::TestBody()::M, false, sqlite_orm::internal::column_t<int TestModulator_TestCount_Test::TestBody()::M::*, sqlite_orm::internal::empty_setter, sqlite_orm::internal::primary_key_with_autoincrement<sqlite_orm::internal::primary_key_t<> > >, sqlite_orm::internal::column_t<int TestModulator_TestCount_Test::TestBody()::M::*, sqlite_orm::internal::empty_setter> >}]’
../sqlite_orm/not_single_header_include/sqlite_orm/../../dev/storage.h:574:22:   required from ‘std::vector<R> sqlite_orm::internal::storage_t<DBO>::select(T, Args ...) [with T = sqlite_orm::internal::count_asterisk_t<TestModulator_TestCount_Test::TestBody()::M>; Args = {}; R = int; DBO = {sqlite_orm::internal::table_t<TestModulator_TestCount_Test::TestBody()::M, false, sqlite_orm::internal::column_t<int TestModulator_TestCount_Test::TestBody()::M::*, sqlite_orm::internal::empty_setter, sqlite_orm::internal::primary_key_with_autoincrement<sqlite_orm::internal::primary_key_t<> > >, sqlite_orm::internal::column_t<int TestModulator_TestCount_Test::TestBody()::M::*, sqlite_orm::internal::empty_setter> >}]’
../sqlite_orm/not_single_header_include/sqlite_orm/../../dev/storage.h:413:22:   required from ‘int sqlite_orm::internal::storage_t<DBO>::count(Args&& ...) [with O = TestModulator_TestCount_Test::TestBody()::M; Args = {}; R = TestModulator_TestCount_Test::TestBody()::M; DBO = {sqlite_orm::internal::table_t<TestModulator_TestCount_Test::TestBody()::M, false, sqlite_orm::internal::column_t<int TestModulator_TestCount_Test::TestBody()::M::*, sqlite_orm::internal::empty_setter, sqlite_orm::internal::primary_key_with_autoincrement<sqlite_orm::internal::primary_key_t<> > >, sqlite_orm::internal::column_t<int TestModulator_TestCount_Test::TestBody()::M::*, sqlite_orm::internal::empty_setter> >}]’
tests/tests.cpp:24:35:   required from here
../sqlite_orm/not_single_header_include/sqlite_orm/../../dev/statement_serializer.h:56:37: error: ambiguous template instantiation for ‘struct sqlite_orm::internal::statement_serializer<sqlite_orm::internal::count_asterisk_t<TestModulator_TestCount_Test::TestBody()::M>, void>’
             statement_serializer<T> serializer;
                                     ^~~~~~~~~~
../sqlite_orm/not_single_header_include/sqlite_orm/../../dev/statement_serializer.h:64:16: note: candidates are: ‘template<class T> struct sqlite_orm::internal::statement_serializer<T, typename std::enable_if<std::integral_constant<bool, is_bindable_v<T> >::value, void>::type> [with T = sqlite_orm::internal::count_asterisk_t<TestModulator_TestCount_Test::TestBody()::M>]’
         struct statement_serializer<T, match_if<is_bindable, T>> {
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../sqlite_orm/not_single_header_include/sqlite_orm/../../dev/statement_serializer.h:439:16: note:                 ‘template<class T> struct sqlite_orm::internal::statement_serializer<sqlite_orm::internal::count_asterisk_t<T>, void> [with T = TestModulator_TestCount_Test::TestBody()::M]’
         struct statement_serializer<count_asterisk_t<T>, void> {
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../sqlite_orm/not_single_header_include/sqlite_orm/../../dev/statement_serializer.h:56:37: error: ‘sqlite_orm::internal::statement_serializer<sqlite_orm::internal::count_asterisk_t<TestModulator_TestCount_Test::TestBody()::M>, void> serializer’ has incomplete type
             statement_serializer<T> serializer;
                                     ^~~~~~~~~~
make: *** [Makefile:60 : tests/tests.o] Erreur 1

```

I compile for arm architectures with --std=c++17 activated

**Comment by trueqbit** [comment] 2023-05-26 18:29
Which compiler and which compiler version do you use, which sqlite_orm version?

**Comment by Falgu9** [comment] 2023-05-30 09:09
I'm using sqlite_orm v1.8.2 and i'm compiling with 
`arm-fsl-linux-gnueabi-g++  -mthumb -mfpu=neon -mfloat-abi=hard -mcpu=cortex-a7 -O2 -pipe -g -feliminate-unused-debug-types -std=c++17`
with gcc version 8.3.0

**Comment by trueqbit** [comment] 2023-05-31 19:58
Thank you for reformatting the error output, it makes the breakdown much easier. :)

Somehow gcc determines that `M` is bindable, i.e. `sqlite_orm::internal::is_bindable<M>::value == true`. Could you please check the value of `is_M_bindable` below:
```c++
constexpr bool is_M_bindable = sqlite_orm::internal::is_bindable<M>::value;
```

Further questions:
1. Why do you pass `-DSQLITE_ORM_OPTIONAL_SUPPORTED -DSQLITE_ORM_STRING_VIEW_SUPPORTED` on the command line? These macros are derived internally.
2. 1. Does it also occur in a minimally reproducible example? (I presume you copied the error output from a slightly more complex test.cpp file because the error output mentions something with line 80).
3. And while we're at it: Do you perhaps have another environment for comparison?

**Comment by Falgu9** [comment] 2023-06-01 08:49
Yeah sorry I'm quite new at this ahah. I actually updated all the examples and made it into the smallest code possible. I've already seen the same errors on a larger code but errors are quite unreadable. I included the "not_single_header_include" instead of the default "include" folder to make it easier to debug. I also updated the command line used to compile, it's not my project so I didn't want to show the full one until I didn't fully understand it.
The path under --sysroot lead to a file system with libraries compiled for arm architecture. I think the problem might be there.

To answer your questions, is_M_bindable is false. I don't really know what it means but here it is.
I passed these two parameters because apparently, when i compile, sqlite_orm thinks __cpp_lib_optional is on an older version, same for __cpp_lib_string_view.

**Comment by trueqbit** [comment] 2023-06-01 17:44
@Falgu9 I found the reason. It has nothing to do with your setup, but this is a problem of older compilers with type names that depend on a template parameter and when this template parameter itself is an alias template.
gcc 8.3 fails, gcc 8.4 works. I have encountered this problem a few times in various contexts, especially with Visual C++.

To be able to investigate the problem, I extracted the essential code from sqlite_orm, which you can see below. Life or death depends on whether `is_bindable<>` is a structure derived from `std::boolean` or an alias template for `std::boolean`.
(For understanding, `is_bindable<>` determines whether sqlite_orm can treat an expression as a sqlite parameter that can be bound to the sql statement; clearly, neither `M` nor `count_asterisk_t<M>`, ... are bindable).

A fix is underway.

```c++
// sqlite_orm 1.8.2, issue #1187

#include <type_traits>
#include <string>

namespace sqlite_orm {
    namespace polyfill = std;

//   310
    namespace internal {
        // enable_if for functions
        template<template<typename...> class Op, class... Args>
        using satisfies = std::enable_if_t<Op<Args...>::value, bool>;

        // enable_if for functions
        template<template<typename...> class Op, class... Args>
        using satisfies_not = std::enable_if_t<polyfill::negation<Op<Args...>>::value, bool>;
    }


    namespace internal {
//  4666
        template<class T>
        struct count_asterisk_t
        {
            using type = T;
        };
    }
    

//  6236
    template<class T>
    internal::count_asterisk_t<T> count() {
        return {};
    }


//  8036
    template<class V, typename Enable = void>
    struct statement_binder;

    namespace internal {

        template<class T, class SFINAE = void>
        inline constexpr bool is_bindable_v = false;
        template<class T>
        inline constexpr bool is_bindable_v<T, polyfill::void_t<decltype(statement_binder<T>())>> = true
            // note : msvc 14.0 needs the parentheses constructor, otherwise `is_bindable<const char*>` isn't recognised.
            // The strangest thing is that this is mutually exclusive with `is_printable_v`.
            ;

        // 1) If `is_bindable` is an alias template, older compilers like gcc 8.3 have problems
        template<class T>
        using is_bindable = polyfill::bool_constant<is_bindable_v<T>>;
        // template<class T>
        // struct is_bindable : polyfill::bool_constant<is_bindable_v<T>> {};
    }


    namespace internal {
//  8285
        struct conditional_binder {
            template<class T, satisfies<is_bindable, T> = true>
            void operator()(const T& t) = delete;

            template<class T, satisfies_not<is_bindable, T> = true>
            void operator()(const T&) const {}
        };
    }
}


struct M {};

using namespace sqlite_orm;

int main() {
    auto c = count<M>();
    internal::conditional_binder binder{};

    // 2) interesting: uncomment this line and the call to `binder` will work, regardless of whether `is_bindable` is an alias template
    // static_assert(!internal::is_bindable_v<internal::count_asterisk_t<M>>);
    binder(c);

    return 0;
}
```
Try it on [godbolt](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1DIApACYAQuYukl9ZATwDKjdAGFUtAK4sGe1wAyeAyYAHI%2BAEaYxCAAHADspAAOqAqETgwe3r56KWmOAkEh4SxRMQm2mPYFDEIETMQEWT5%2BXJXVGXUNBEVhkdF6CvWNzTltQ929JWUSAJS2qF7EyOwcAPRrANQKAI60hJgA%2BiQsm1wAdLHnZqSbeAoKXpib5gDMXFwJJhoAgt9/ZlewWQ3iwL1ebgIAE8kkcCMQmIQFCZXth/m9gaDnii3ENiMFgCi0b9/sw2AokkwVts9gdjsRTiZ4lZfps2ZsyZgKVTnilaFCaLRaOCACLbAjoFEsv6/Dbs94af7sjmsLmU6nBAjRZjCpnS5XKuWMJgReiHPBUTb8YhWrwMBwZZGsg1srUsJIGLU4t0epheiHQ2Gc84hombEFMB6bADySVuEYeIfOmx%2BxGAyNRSpdmy8aSM2z99xoXNF4vQIBAxtNRwthwIONjONT6aTRIrADcxE9bhFUJ4iVL0c6XUbmNXzZbrbb7TUnT9s5sfZ7MN7MO7l96Yca2K3UeGDFHY/GDwokym0xnifPs7mCQXHApiwpDgxUARS0Ny5Wx2ba/WIXyAp0LQFYhMAhYCA2SRNheu5oqiHZdpgPZ9rQA6vPq7JMiKQ4ytebKctyGqCNqYgvMy/xypskgAGx0VmLpLn6K4QgmCibAAKgOw4GniXgOOGiyCIckZaviCgANZ1gxBp6jJC63vmgbYq8YpcRh8lYfEOEaTx2EybhVE0YCNEyUx/puGxnHcfhdwkcQOoVmgdoECJQzRPcUn/m46nYIJLkQLM5GYS6xCYAQSwMMF%2Bm6bZ%2BkkglPxUbEGivKZPHmSxlknpsABqtzKZymzYD%2BKliu2qB4JKmY8XxAkTG6jCuREwRYMQg6JcqhHqs8mqkbqFGddmmU4lZHHHpG7FCAAYgAkqEPx%2BSi5WVdVV4LsE%2BwhIJDDuaoSQ2r2nh3M%2BLUMOgJpmu2pZUGISgdbZyojaxOW%2BZpbKbcEzxoLtWr7YdqEnYcZ0XeO7Y4uNmyAYKIEgBVVXSRCWAgspEANWuTXA610QQ0SgWzOhS2qYuxBPO9Bpyq%2BWqbCAmwsAo7bIGckjnBoHKYJg6DsQQCC8g0TW80o7E/XVRBkJsb688QADu9zYjRGj3Fj52XVlIvvsgCANAAVAOCsnQwYAcO%2BYVoMADBy%2Bg5zk4aWwcbz4oIkYXLvjzd73IuWuuwgHseywXgRWI/KbJgqggre7bPLLPMvArSsHZqquHODCvWzxC4PeTcpcEFs2WiYcena1qsF2zHuGJsYh4JGi5rr6Wq3J4bWCe6dDROx%2BwSc8wDIEzVyvJsWuR1DxCoNW9Pk892WTdZNWPeyinAEDIOq6W0PARWR20Ic6uGN5Ssr2DuOZifIUU1sU9jTZC5yqLy/F9WNNQ54QFCpvqE7wIEyCDiB8P1dx94JLQotpB6yp4p4Rkt1HkdkxI6mirKLYmxYhmFiAAVnJnfH6%2BAahiGVs3OS6dhp1w3C9GekMFCFkfHgLkv8i4q2rLcXypZ4RkznguZU8N0AS1hAiMWgUIDq2smYGii4grLU2Fgeg/ppQ23ZJfV6txKEPifC%2BN8dD8GqyYWGCRrCWLrQ4WyLhPDoh%2BhIAIoRXERFBSEXJUBRC2QxTPhAlxiU74AFloqgNiv8ReKpyQ9RpPsLU9IWCZ1%2BJqOmiIGCBQQbZJgAdUDhlLM5H%2BEJ3F4wJrFZUfUHJiCcgIHBGQ8Eg2iJsUp7UQE6VkTxOUZggq5JdgSWmdo0AsDYIIT2HstrPEMNwnm30g6LiSaXCppdNiyyFBMkgElbhhXAsQdA9AoyoEtNLXmAybSlz/gw%2Bg4zy5RSrjXEatStgNTwMgNyShGgQDAGAXJjkQA7NBgAiEDz8koCEq5USHlJKIzcBkk%2B2AslnwqYIkFuFlRhQig5TYiofH2J%2BBweYIEOBoN4H4DgWhSCoE4G4aw1htiLGWNiQEPBSAEE0Mi%2BYEkQCvBZmgyQaCUEfBolwNKsQKioskBiqlOLOC8AUCADQFKqXzDgLAJAbSkhtzIBQQRqBW70BiMAWIrxSBYHbBczAuUaHS1jIwTg5LBRiSFRACIfKzoNChEa3gVriBQmjBEbQmAHC2tIG0jpBBowMH5HyrAEQvDADcEHIV3BeBYBYIYYA4gsURrwKbRwkcw3YtDq6gOqxyV9VRdi/YEQEQOo8FgPl8I8AsFtfMKgBh0y6swPqoM7r%2BCCBEGIdgUgZCCEUCodQcbSC6DaAYIwKACWWH0HgCIQrIDzFQEkWcnAAC0n5lqmEsNYLg8ReCoEjsQfEWBJ2BXaK6moLhzqjFaKQQIX1pgDDaHkdIAgz25FSPehgUx%2BgxHGFUI9nRhhNE8C0QYX6HQCC6I0N9pQb22F/Y%2B8Yv7wMzBzgsJYKw5j6E4Oi0gmLsW4o4JsVQsQaLzpopITYPc%2B7nAHhAXAhASAvDJbMXglK42zBpSAMwABOVmqCFY0XiBoeI672OxHY%2Bq7lvLe04cFcK0VzHSASsQCARYBAkgB3IJQaVsrQiqk4D8AASp4sjyCKPnC4JsCAr4QgMYvTgkgVU9BNuEKIcQ7aHNdrUHy/tpBpYIiSBWtDaLxPYc4NGAOKn3yrLwwRojJHDP9zMx4JVZS3g50Y2K1jaVziSDMGgtB8QzDsqkGgrgZgbhicw3yyTthpNMa0Cx/zZhAuboFTJ2r8xt1pGcJIIAA%3D%3D%3D).

**Comment by fnc12** [comment] 2023-09-25 06:54
@Falgu9 we need you confirmation whether it works with fresh `dev` branch or not

**Comment by trueqbit** [comment] 2023-10-08 22:49
> @Falgu9 we need you confirmation whether it works with fresh `dev` branch or not

He [confirmed](https://github.com/fnc12/sqlite_orm/pull/1188#issuecomment-1573455740) that it works in the PR branch. So I think we can close this issue...

**Closed** 2023-10-09 04:45 UTC
Labels: bug
